<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>RhythmBase</RootNamespace>
		<AssemblyName>RhythmBase.Rizline</AssemblyName>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<Title>RhythmBase.Rizline</Title>
		<Version>1.3.11-alpha9</Version>
		<RhythmBaseVersion Condition="'$(RhythmBaseVersion)' == ''">1.3.11-alpha9</RhythmBaseVersion>
		<Authors>obugs</Authors>
		<Description>Rizline level adapter for RhythmBase. Provides event model, multi-file serialization, and versioned level support for Rizline levels.</Description>
		<PackageProjectUrl>https://github.com/RDCN-Community-Developers/RhythmToolkit</PackageProjectUrl>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageTags>Rhythm Game;Rizline</PackageTags>
		<PackageReleaseNotes>VERSION.md</PackageReleaseNotes>
		<PackageIcon>RhythmBase_logo_small.png</PackageIcon>
		<RepositoryUrl>https://github.com/RDCN-Community-Developers/RhythmToolkit.git</RepositoryUrl>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<LangVersion>Preview</LangVersion>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<IsAotCompatible>true</IsAotCompatible>
		<VerifyReferenceAotCompatibility>true</VerifyReferenceAotCompatibility>
		<EmitCompilerGeneratedFiles Condition="'$(Configuration)'=='Debug'">true</EmitCompilerGeneratedFiles>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="RhythmBase" Version="$(RhythmBaseVersion)" />
		<None Include="../README.md;../README.zh-cn.md;../VERSION.md;../VERSION.zh-cn.md;../RhythmBase_logo_small.png;../RhythmBase_logo.png;../RhythmBase_logo_clean.png;../RhythmBase_banner.png;../RhythmBase_banner_clean.png;../LICENSE.txt;" Pack="True" PackagePath="/" />
		<Compile Include="../DotnetCompatibility.cs"></Compile>
	</ItemGroup>
</Project>
