using RhythmBase.RhythmDoctor.Events;
namespace RhythmBase.RhythmDoctor.Components;


/// <summary>
/// Represents the method that handles the event raised when a new event is added to an RDLevel instance.
/// </summary>
/// <remarks>Use this delegate to subscribe to notifications when events are added, enabling custom processing
/// of new events as they occur.</remarks>
/// <param name="level">The RDLevel instance to which the event is being added.</param>
/// <param name="e">An RDEventArgs object that contains the data associated with the added event.</param>
public delegate void RDEventHandler(RDLevel level, RDEventArgs e);

/// <summary>
/// Provides data for events related to Rhythm Doctor events in the system, encapsulating the associated event and metadata
/// about its origin.
/// </summary>
/// <remarks>
/// Initializes a new instance of the RDEventArgs class with the specified event.
/// </remarks>
/// <param name="e">The event that this RDEventArgs instance represents. This parameter cannot be null.</param>
public class RDEventArgs(IBaseEvent e) : EventArgs
{
	/// <summary>
	/// Gets the event associated with this instance.
	/// </summary>
	/// <remarks>Use this property to access event-specific data and functionality. The returned event may be null
	/// if no event is currently associated with the instance.</remarks>
	public IBaseEvent Event { get; } = e;
	/// <summary>
	/// Gets or sets a value indicating whether the event is automatically populated.
	/// </summary>
	/// <remarks>
	/// It will be true if the event is automatically added to the level as a result of adding another event that requires it
	/// (e.g., a SetCrotchetsPerBar event added due to adding a CPB change).
	/// This property can be used by event handlers to determine whether the event was explicitly added by the user or
	/// automatically generated by the system, allowing for different handling logic if necessary.
	/// </remarks>
	public bool IsAutoPopulated { get; set; }
}
