// <auto-generated/>
#nullable enable
namespace RhythmBase._g_registryId_;

/// <summary>
/// Defines how a chart name maps to its file name within a level. Each format defines this
/// naming rule; implement a concrete subclass with the game's convention, for example
/// <c>easy</c> ↔ <c>chart-easy.json</c>.
/// </summary>
internal abstract partial class ChartFileNaming
{
	/// <summary>
	/// Gets the file name used to store the chart with the given name.
	/// </summary>
	public abstract string GetFileName(string chartName);
	/// <summary>
	/// Tries to map a file name back to a chart name.
	/// </summary>
	/// <param name="fileName">The file name to inspect.</param>
	/// <param name="chartName">The chart name if the file is a chart file; otherwise empty.</param>
	/// <returns><c>true</c> if the file name belongs to a chart; otherwise, <c>false</c>.</returns>
	public abstract bool TryGetChartName(string fileName, out string chartName);
}
