// <auto-generated/>
#nullable enable
namespace _g_calculatorNamespace_;

internal record struct BpmCache(float Tick, TimeSpan TimeSpan, float Bpm) : IComparable<BpmCache>
{
	public static readonly BpmCache Default = new(1, TimeSpan.Zero, RhythmBase._g_registryId_.Constants.DefaultBpm);
	public readonly int CompareTo(BpmCache other) => Tick.CompareTo(other.Tick);
}

/// <summary>
/// Beat calculator that converts between absolute ticks and time spans, while reacting to tempo and BPM changes.
/// </summary>
public partial class _g_calculatorSymbolName_
{
	internal readonly _g_Chart_ Collection;
	private BpmCache[] _bpmCache = [];
	internal _g_calculatorSymbolName_(_g_Chart_ chart)
	{
		Collection = chart;
	}
	internal void AddBpmAt(BpmCache bpm)
	{
		if (_bpmCache.Length == 0)
		{
			_bpmCache = [bpm];
			return;
		}
		int index = _bpmCache.BinarySearch(bpm);
		if (index < 0) index = ~index - 1;

		BpmCache a, b;
		if (index < 0) a = BpmCache.Default;
		else a = _bpmCache[index];
		if (a.Tick == bpm.Tick && (a.Bpm == bpm.Bpm)) return;
		if (index >= _bpmCache.Length - 1)
		{
			_bpmCache = [.. _bpmCache, bpm];
			return;
		}
		else
		{
			b = _bpmCache[index + 1];
			TimeSpan diff = TimeSpan.FromMinutes((b.Tick - bpm.Tick) / bpm.Bpm) - (b.TimeSpan - bpm.TimeSpan);
			for (int i = index + 1; i < _bpmCache.Length; ++i)
			{
				BpmCache ti = _bpmCache[i];
				ti.TimeSpan += diff;
				_bpmCache[i] = ti;
			}
			if (a.Tick != bpm.Tick)
				_bpmCache = [.. _bpmCache[..(index + 1)], bpm, .. _bpmCache[(index + 1)..]];
			else if (index < 0)
				_bpmCache = [bpm, .. _bpmCache];
			else
				_bpmCache[index] = bpm;
			return;
		}
	}
	internal void RemoveBpmAt(BpmCache bpm)
	{
		if (_bpmCache.Length == 0)
			return;
		int index = _bpmCache.BinarySearch(bpm);
		if (index < 0) return;
		BpmCache a, b;
		if (index == 0) a = BpmCache.Default;
		else a = _bpmCache[index - 1];
		if (index == _bpmCache.Length - 1)
		{
			_bpmCache = [.. _bpmCache[..(_bpmCache.Length - 1)]];
			return;
		}
		else
		{
			b = _bpmCache[index + 1];
			TimeSpan diff = TimeSpan.FromMinutes((b.Tick - bpm.Tick) / a.Bpm) - (b.TimeSpan - bpm.TimeSpan);
			for (int i = index + 1; i < _bpmCache.Length; ++i)
			{
				BpmCache ti = _bpmCache[i];
				ti.TimeSpan += diff;
				_bpmCache[i] = ti;
			}
			_bpmCache = [.. _bpmCache[..index], .. _bpmCache[(index + 1)..]];
			return;
		}
	}
	/// <summary>
	/// Refreshes the caches so subsequent conversions use up-to-date values.
	/// </summary>
	public partial void Refresh();

	/// <summary>
	/// Converts an absolute tick position to an absolute timespan using the current cache state.
	/// </summary>
	/// <param name="tick">The absolute tick position.</param>
	/// <returns>The corresponding absolute time.</returns>
	public TimeSpan TickToTimeSpan(float tick) => TickToTimeSpan(tick, in _bpmCache);
				
	/// <summary>
	/// Converts an absolute timespan to an absolute beat position using the current cache state.
	/// </summary>
	/// <param name="timeSpan">The absolute time to convert.</param>
	/// <returns>The corresponding absolute beat.</returns>
	public float TimeSpanToTick(TimeSpan timeSpan) => TimeSpanToTick(timeSpan, in _bpmCache);

	private static TimeSpan TickToTimeSpan(float tick, in BpmCache[] cacheSet)
	{
		BpmCache last = BpmCache.Default;
		foreach (BpmCache cache in cacheSet)
		{
			float cbeat = cache.Tick;
			if (cbeat < tick)
			{
				last = cache;
				continue;
			}
			if (cbeat == tick)
				return cache.TimeSpan;
			break;
		}
		float durationFromLast = (tick - last.Tick) / last.Bpm;
		TimeSpan result = last.TimeSpan + TimeSpan.FromMinutes(durationFromLast);
		return result;
	}
	private static float TimeSpanToTick(TimeSpan timeSpan, in BpmCache[] cacheSet)
	{
		BpmCache last = BpmCache.Default;
		foreach (BpmCache cache in cacheSet)
		{
			TimeSpan ctime = cache.TimeSpan;
			if (ctime < timeSpan)
			{
				last = cache;
				continue;
			}
			if (ctime == timeSpan)
				return cache.Tick;
			break;
		}
		float tick = last.Tick + (float)((timeSpan - last.TimeSpan).TotalMinutes * last.Bpm);
		return tick;
	}

	/// <summary>
	/// Creates an <see cref="_g_TickTime_"/> from an absolute tick value.
	/// </summary>
	/// <param name="tick">The absolute tick position.</param>
	/// <returns>An <see cref="_g_TickTime_"/> bound to this calculator.</returns>
	public _g_TickTime_ TickOf(float tick) => new(this, tick);

	/// <summary>
	/// Creates an <see cref="_g_TickTime_"/> from an absolute timespan.
	/// </summary>
	/// <param name="timeSpan">The absolute time to convert.</param>
	/// <returns>An <see cref="_g_TickTime_"/> bound to this calculator.</returns>
	public _g_TickTime_ TickOf(TimeSpan timeSpan) => new(this, timeSpan);

	/// <summary>
	/// Creates a <see cref="_g_TickTimeRange_"/> representing the interval between two ticks.
	/// </summary>
	/// <param name="tick1">The starting tick.</param>
	/// <param name="tick2">The ending tick.</param>
	/// <returns>The resulting interval.</returns>
	public _g_TickTimeRange_ IntervalOf(_g_TickTime_ tick1, _g_TickTime_ tick2) => new(new(this, tick1), new(this, tick2));

	/// <summary>
	/// Creates a <see cref="_g_TickTimeRange_"/> representing the interval between two timespans.
	/// </summary>
	/// <param name="timeSpan1">The start time.</param>
	/// <param name="timeSpan2">The end time.</param>
	/// <returns>The resulting interval.</returns>
	public _g_TickTimeRange_ IntervalOf(TimeSpan timeSpan1, TimeSpan timeSpan2) => IntervalOf(TickOf(timeSpan1), TickOf(timeSpan2));
	/// <summary>
	/// Gets the BPM in effect at the specified tick.
	/// </summary>
	/// <param name="beat">The tick whose BPM should be retrieved.</param>
	/// <returns>The BPM active at the tick.</returns>
	public float BeatsPerMinuteOf(_g_TickTime_ beat)
	{
		BpmCache last = BpmCache.Default;
		foreach (BpmCache cache in _bpmCache)
		{
			float cbeat = cache.Tick;
			if (cbeat < beat.Tick)
			{
				last = cache;
				continue;
			}
			if (cbeat == beat.Tick)
				return cache.Bpm;
			break;
		}
		return last.Bpm;
	}
}
