// <auto-generated/>
#nullable enable
namespace RhythmBase._g_registryId_;

/// <summary>
/// Provides constant values in the game.
/// </summary>
public static partial class Constants
{
	/// <summary>
	/// The default beats per minute for a new chart.
	/// </summary>
	public static partial float DefaultBpm { get; }
}
