// <auto-generated/>
#nullable enable
namespace RhythmBase._g_registryId_.Components;


/// <summary>
/// Represents a collection of events that can be enumerated.
/// </summary>
/// <typeparam name="TEvent">The type of events in the collection. Must implement <see cref="_g_IBaseEvent_"/>.</typeparam>
public interface IEventEnumerable<out TEvent>
		: IEnumerable<TEvent>
		where TEvent : _g_IBaseEvent_
{
	/// <summary>
	/// Gets the events organized by beat order.
	/// </summary>
	RhythmBase.Global.Components.RedBlackTree<_g_TickTime_, TypedEventCollection> EventsBeatOrder { get; }
	/// <summary>
	/// Gets the bounds of the events in the collection.
	/// </summary>
	_g_TickTimeRange_ Range { get; }
	/// <summary>
	/// Gets the type of events in the collection.
	/// </summary>
	RhythmBase.Global.Components.ReadOnlyEnumCollection<_g_EventType_> Types { get; }
}


/// <summary>
/// Represents a collection of typed events.
/// </summary>
public class TypedEventCollection : IEnumerable<_g_IBaseEvent_>
{
	/// <summary>
	/// Gets the number of events in the collection.
	/// </summary>
	public int Count => list.Count;
	/// <inheritdoc />
	public RhythmBase.Global.Components.ReadOnlyEnumCollection<_g_EventType_> Types => _types.AsReadOnly();
	/// <summary>
	/// Initializes a new instance of the <see cref="TypedEventCollection"/> class.
	/// </summary>
	public TypedEventCollection() { }
	/// <summary>
	/// Adds an event to the collection.
	/// </summary>
	/// <param name="item">The event to add.</param>
	/// <returns>true if the event was added; otherwise, false if it already exists.</returns>
	public virtual bool Add(_g_IBaseEvent_ item)
	{
		if (list.Contains(item))
			return false;
		list.Add(item);
		_types.Add(item.Type);
		return true;
	}
	/// <summary>
	/// Removes an event from the collection.
	/// </summary>
	/// <param name="item">The event to remove.</param>
	/// <returns>true if the event was removed; otherwise, false.</returns>
	public virtual bool Remove(_g_IBaseEvent_ item)
	{
		bool result = list.Remove(item);
		if (!result)
			return false;
		if (!list.Any(i => i.Type == item.Type))
			_types.Remove(item.Type);
		return true;
	}
	/// <summary>Determines whether this bucket contains any event of the specified type.</summary>
	[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
	public bool ContainsType(_g_EventType_ type) => _types.Contains(type);
	/// <summary>Determines whether this bucket contains any event of the specified types.</summary>
	[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
	public bool ContainsTypes(_g_EventType_[] types) => _types.ContainsAny(types);
	/// <summary>Determines whether this bucket contains any event matching the given type collection.</summary>
	[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
	public bool ContainsTypes(ReadOnlyEnumCollection<_g_EventType_> types) => _types.ContainsAny(types);
	/// <summary>Compares the insertion order of two events within this bucket.</summary>
	[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
	public bool CompareTo(_g_IBaseEvent_ item1, _g_IBaseEvent_ item2) =>
			list.IndexOf(item1) < list.IndexOf(item2);
	/// <summary>
	/// Returns a string that represents the current collection.
	/// </summary>
	/// <returns>A string that represents the current collection.</returns>
	public override string ToString()
	{
		string result = $"Count={list.Count}";
		return result;
	}
	/// <summary>
	/// Returns an enumerator that iterates through the collection.
	/// </summary>
	/// <returns>An enumerator that can be used to iterate through the collection.</returns>
	public IEnumerator<_g_IBaseEvent_> GetEnumerator() =>
			list.GetEnumerator();
	System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() =>
			list.GetEnumerator();
	private readonly List<_g_IBaseEvent_> list = [];
	private readonly RhythmBase.Global.Components.EnumCollection<_g_EventType_> _types = [];
}

/// <summary>
/// Provides an enumerator over events in a <see cref="RhythmBase.Global.Components.RedBlackTree{TKey, TValue}"/> collection, filtered by
/// event types and an optional tick range.
/// </summary>
/// <typeparam name="TEvent">The event interface type to enumerate.</typeparam>
public class EventEnumerator<TEvent>(RhythmBase.Global.Components.RedBlackTree<_g_TickTime_, TypedEventCollection> collection, RhythmBase.Global.Components.ReadOnlyEnumCollection<_g_EventType_> types, _g_TickTimeRange_ range)
		: IEventEnumerable<TEvent>, IEnumerator<TEvent>
	where TEvent : _g_IBaseEvent_
{
	/// <summary>
	/// The enumerator over beat-keyed buckets in the tree.
	/// </summary>
	protected readonly IEnumerator<KeyValuePair<_g_TickTime_, TypedEventCollection>> beats = collection.GetEnumerator();
	/// <summary>
	/// The enumerator over events within the current bucket, or <c>null</c> if no bucket is active.
	/// </summary>
	protected IEnumerator<_g_IBaseEvent_>? events;
	/// <summary>
	/// The underlying tree collection.
	/// </summary>
	protected readonly RhythmBase.Global.Components.RedBlackTree<_g_TickTime_, TypedEventCollection> collection = collection;
	private RhythmBase.Global.Components.ReadOnlyEnumCollection<_g_EventType_> types = types;
	private _g_TickTimeRange_ range = range;
	RhythmBase.Global.Components.ReadOnlyEnumCollection<_g_EventType_> IEventEnumerable<TEvent>.Types => types;
	_g_TickTimeRange_ IEventEnumerable<TEvent>.Range => range;
	/// <inheritdoc/>
	public TEvent Current => ((TEvent?)events?.Current) ?? throw new InvalidOperationException();
	/// <inheritdoc/>
	object System.Collections.IEnumerator.Current => Current;
	RhythmBase.Global.Components.RedBlackTree<_g_TickTime_, TypedEventCollection> IEventEnumerable<TEvent>.EventsBeatOrder => collection;
	/// <inheritdoc/>
	public bool MoveNext()
	{
		if (events != null)
		{
			while (events.MoveNext())
			{
				if (types.Contains(events.Current.Type))
					return true;
			}
			events = null;
		}
		while (beats.MoveNext())
		{
			var currentKey = beats.Current.Key;

			if (range.Start.HasValue && currentKey.CompareTo(range.Start.Value) < 0)
				continue;
			if (range.End.HasValue && currentKey.CompareTo(range.End.Value) >= 0)
				return false;
			if (!beats.Current.Value.ContainsTypes(types))
				continue;
			events = beats.Current.Value.GetEnumerator();
			while (events.MoveNext())
			{
				if (types.Contains(events.Current.Type))
					return true;
			}
			events = null;
		}
		return false;
	}
	private bool _disposed = false;
	/// <summary>
	/// Disposes the enumerator, releasing any resources held by the beat and event enumerators.
	/// </summary>
	/// <param name="disposing"><c>true</c> to release both managed and unmanaged resources; <c>false</c> to release only unmanaged resources.</param>
	protected virtual void Dispose(bool disposing)
	{
		if (_disposed) return;
		if (disposing)
		{
			beats.Dispose();
			events?.Dispose();
		}
		_disposed = true;
	}
	/// <inheritdoc/>
	public void Dispose()
	{
		Dispose(true);
		GC.SuppressFinalize(this);
	}
	/// <inheritdoc/>
	public void Reset() => throw new NotSupportedException();
	/// <summary>
	/// Narrows the enumeration to events of the specified target type, intersecting the current type filter.
	/// </summary>
	/// <typeparam name="TTarget">The more specific event type to filter for.</typeparam>
	/// <returns>A new <see cref="IEventEnumerable{TTarget}"/> with the narrowed filter.</returns>
	public IEventEnumerable<TTarget> OfEvent<TTarget>() where TTarget : _g_IBaseEvent_
	{
		RhythmBase.Global.Components.ReadOnlyEnumCollection<_g_EventType_> types = this.types.Intersect(RhythmBase._g_registryId_.Serialization.EventTypeRegistry.ToEnums_g_eventTypeRegistryMethodSuffix_<TTarget>());
		this.types = types;
		return new EventEnumerator<TTarget>(collection, types, range);
	}
	/// <summary>
	/// Replaces the current type filter with the specified collection of event types.
	/// </summary>
	/// <param name="types">The event types to enumerate.</param>
	/// <returns>This enumerator with the updated filter.</returns>
	public IEventEnumerable<_g_IBaseEvent_> OfEvents(RhythmBase.Global.Components.ReadOnlyEnumCollection<_g_EventType_> types)
	{
		this.types = types;
		return new EventEnumerator<_g_IBaseEvent_>(collection, types, range);
	}
	/// <summary>
	/// Narrows the enumeration to the specified tick range, intersecting with the current range.
	/// </summary>
	/// <param name="range">The tick range to filter for.</param>
	/// <returns>This enumerator with the narrowed range.</returns>
	public IEventEnumerable<TEvent> InRange(_g_TickTimeRange_ range)
	{
		this.range = this.range.Intersect(range);
		return this;
	}
	/// <summary>
	/// Returns all events at the specified beat that match the current type filter.
	/// </summary>
	/// <param name="beat">The beat at which to retrieve events.</param>
	/// <returns>An enumerable of matching events at the given beat.</returns>
	public IEnumerable<TEvent> AtBeat(_g_TickTime_ beat)
	{
		if (!range.Contains(beat))
			yield break;
		if (!collection.TryGetValue(beat, out var events))
			yield break;
		if (!events.ContainsTypes(types))
			yield break;
		foreach (var ev in events)
			if (types.Contains(ev.Type))
				yield return (TEvent)ev;
	}
	/// <inheritdoc/>
	public IEnumerator<TEvent> GetEnumerator() => this;
	/// <inheritdoc/>
	System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() => GetEnumerator();
}

/// <summary>
/// Represents a collection of ordered events.
/// </summary>
/// <typeparam name="TEvent">The type of event.</typeparam>
public abstract class OrderedEventCollection<TEvent> : ICollection<TEvent>, IEventEnumerable<TEvent>
		where TEvent : _g_IBaseEvent_
{
	/// <summary>
	/// Initializes a new instance of the <see cref="OrderedEventCollection{TEvent}"/> class.
	/// </summary>
	public OrderedEventCollection()
	{
		EventsBeatOrder = [];
		IsReadOnly = false;
	}
	/// <summary>
	/// Concatenates all events in the collection.
	/// </summary>
	/// <returns>An <see cref="IEnumerable{TEvent}"/> that contains all events in the collection.</returns>
	public IEnumerable<TEvent> ConcatAll() => EventsBeatOrder.SelectMany(i => i.Value).Cast<TEvent>();
	void ICollection<TEvent>.Add(TEvent item) => Add(item);
	/// <inheritdoc/>  
	public override string ToString() => $"Count = {Count}";
	///// <inheritdoc/>
	//public override IEnumerator<_g_IBaseEvent_> GetEnumerator() => (IEnumerator<_g_IBaseEvent_>)new EventEnumerator<TEvent>(this);
	/// <inheritdoc/>  
	public IEnumerator<TEvent> GetEnumerator()
	{
		foreach (KeyValuePair<_g_TickTime_, TypedEventCollection> pair in EventsBeatOrder)
			foreach (TEvent item in pair.Value)
				yield return item;
	}
	/// <summary>
	/// Gets the total count of events in the collection.
	/// </summary>
	public virtual int Count => EventsBeatOrder.Sum(i => i.Value.Count);
	/// <summary>
	/// Gets a value indicating whether the collection is read-only.
	/// </summary>
	public bool IsReadOnly { get; }
	/// <summary>
	/// Returns the beat of the last event.
	/// </summary>
	/// <returns>The beat of the last event.</returns>
	public _g_TickTime_ Duration => EventsBeatOrder.LastOrDefault().Key;

	/// <summary>
	/// Initializes a new instance of the <see cref="OrderedEventCollection{TEvent}"/> class with the specified items.
	/// </summary>
	/// <param name="items">The items to add to the collection.</param>
	public OrderedEventCollection(IEnumerable<TEvent> items)
	{
		EventsBeatOrder = [];
		IsReadOnly = false;
		foreach (TEvent item in items)
			Add(item);
	}
	/// <summary>
	/// Adds an event to the collection.
	/// </summary>
	/// <param name="item">The event to add.</param>
	public virtual bool Add(TEvent item)
	{
		if (EventsBeatOrder.TryGetValue(item.TickTime, out TypedEventCollection? value))
			return value.Add(item);
		EventsBeatOrder.Insert(item.TickTime, [item]);
		return true;
	}
	/// <summary>
	/// Clears all events from the collection.
	/// </summary>
	public void Clear() => EventsBeatOrder.Clear();
	/// <summary>
	/// Determines whether the collection contains a specific event.
	/// </summary>
	/// <param name="item">The event to locate in the collection.</param>
	/// <returns>true if the event is found in the collection; otherwise, false.</returns>
	public virtual bool Contains(TEvent item) => EventsBeatOrder.FindNode(item.TickTime)?.Value.Contains(item) ?? false;
	/// <summary>
	/// Copies the elements of the collection to an array, starting at a particular array index.
	/// </summary>
	/// <param name="array">The array to copy the elements to.</param>
	/// <param name="arrayIndex">The zero-based index in the array at which copying begins.</param>
	public void CopyTo(TEvent[] array, int arrayIndex)
	{
		if (arrayIndex < 0 || arrayIndex > array.Length)
			throw new ArgumentOutOfRangeException(nameof(arrayIndex));
		if (array.Length - arrayIndex < Count)
			throw new ArgumentException("The number of elements in the source collection is greater than the available space from arrayIndex to the end of the destination array.");
		foreach (KeyValuePair<_g_TickTime_, TypedEventCollection> pair in EventsBeatOrder)
		{
			foreach (TEvent item in pair.Value)
			{
				array[arrayIndex++] = item;
			}
		}
	}
	/// <summary>
	/// Removes the first occurrence of a specific event from the collection.
	/// </summary>
	/// <param name="item">The event to remove from the collection.</param>
	/// <returns>true if the event was successfully removed; otherwise, false.</returns>
	public virtual bool Remove(TEvent item)
	{
		bool Remove;
		if (Contains(item))
		{
			bool result = EventsBeatOrder[item.TickTime].Remove(item);
			if (EventsBeatOrder[item.TickTime].Count == 0)
				EventsBeatOrder.Remove(item.TickTime);
			Remove = result;
		}
		else
			Remove = false;
		return Remove;
	}
	internal IEnumerator<TEvent> GetEnumerator(_g_TickTime_? start, _g_TickTime_? end) => new EventEnumerator<TEvent>(EventsBeatOrder, Types, new _g_TickTimeRange_(start, end));
	/// <summary>
	/// Returns an enumerator that iterates through the collection.
	/// </summary>
	/// <returns>An enumerator for the collection.</returns>
	System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() => GetEnumerator();
	/// <summary>
	/// Removes the first occurrence of a specific event from the collection.
	/// </summary>
	/// <param name="item">The event to remove from the collection.</param>
	/// <returns>true if the event was successfully removed; otherwise, false.</returns>
	bool ICollection<TEvent>.Remove(TEvent item) => throw new NotImplementedException();
	/// <summary>
	/// The dictionary that maintains the order of events based on their beats.
	/// </summary>
	[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
	public RhythmBase.Global.Components.RedBlackTree<_g_TickTime_, TypedEventCollection> EventsBeatOrder = [];
	RhythmBase.Global.Components.RedBlackTree<_g_TickTime_, TypedEventCollection> IEventEnumerable<TEvent>.EventsBeatOrder => EventsBeatOrder;
	/// <summary>Gets the collection of event types supported by this collection.</summary>
	public RhythmBase.Global.Components.ReadOnlyEnumCollection<_g_EventType_> Types => RhythmBase._g_registryId_.Serialization.EventTypeRegistry.ToEnums_g_eventTypeRegistryMethodSuffix_<TEvent>();
	_g_TickTimeRange_ IEventEnumerable<TEvent>.Range => _g_TickTimeRange_.Infinity;
}


