// <auto-generated/>
#nullable enable
namespace _g_chartNamespace_;

/// <summary>
/// Specialized chart members with the adapter's concrete types.
/// </summary>
public partial class _g_chartSymbolName_
{
	/// <summary>
	/// Gets the level that owns this chart, or <c>null</c> if the chart is standalone.
	/// </summary>
	public _g_levelSymbolToDisplayString_? ParentLevel => _parentLevel;
	internal _g_levelSymbolToDisplayString_? _parentLevel;
}
