// <auto-generated/>
namespace _g_tickTimeNamespace_;

/// <summary>
/// Beat range.
/// </summary>
public struct _g_TickRangeName_
{
	/// <summary>
	/// Start beat.
	/// </summary>
	public _g_TickTime_? Start { get; }
	/// <summary>
	/// End beat.
	/// </summary>
	public _g_TickTime_? End { get; }
	/// <summary>
	/// Beat interval.
	/// </summary>
	public readonly float BeatInterval
	{
		get
		{
			float BeatInterval = Start is _g_TickTime_ startNotNull && End is _g_TickTime_ endNotNull
					? endNotNull.Tick - startNotNull.Tick
					: float.PositiveInfinity;
			return BeatInterval;
		}
	}
	/// <summary>
	/// Time interval.
	/// </summary>
	public readonly TimeSpan TimeInterval
	{
		get
		{
			bool flag = Start != null && End != null;
			TimeSpan TimeInterval;
			if (flag)
			{
				if (Start!.Value.Tick == End!.Value.Tick)
				{
					TimeInterval = TimeSpan.Zero;
				}
				else
				{
					TimeInterval = End.Value.TimeSpan - Start.Value.TimeSpan;
				}
			}
			else
			{
				TimeInterval = TimeSpan.MaxValue;
			}
			return TimeInterval;
		}
	}
	/// <summary>
	/// Initializes a new instance of the <see cref="_g_TickRangeName_"/> struct with the specified start and end beats.
	/// </summary>
	/// <param name="start">Start beat.</param>
	/// <param name="end">End beat.</param>
	public _g_TickRangeName_(_g_TickTime_? start, _g_TickTime_? end)
	{
		this = default;
		if (start != null && end != null && !((_g_TickTime_)start).FromSameChartOrNull((_g_TickTime_)end))
		{
			throw new InvalidOperationException("RDIndexes must come from the same RDLevel.");
		}
		if (start != null && end != null && start > end)
		{
			Start = end;
			End = start;
		}
		else
		{
			Start = start;
			End = end;
		}
	}
	/// <summary>
	/// Determines whether the specified beat is within the range.
	/// </summary>
	/// <param name="b">The beat to check.</param>
	/// <returns>True if the beat is within the range; otherwise, false.</returns>
	public readonly bool Contains(_g_TickTime_ b) => (Start == null || Start <= b) && (End == null || b < End);
	/// <summary>
	/// Computes the intersection of the current range with another specified range.
	/// </summary>
	/// <remarks>The intersection of two ranges is the range that contains all elements common to both ranges.  If
	/// either range is unbounded (i.e., has a null start or end), the resulting range will reflect  the bounds of the
	/// other range where applicable. If the resulting range is invalid  (i.e., the start is greater than the end), an
	/// empty range is returned.</remarks>
	/// <param name="other">The range to intersect with the current range.</param>
	/// <returns>A new <see cref="_g_TickRangeName_"/> representing the intersection of the two ranges.  If the ranges do not overlap,
	/// returns an empty range.</returns>
	public readonly _g_TickRangeName_ Intersect(_g_TickRangeName_ other)
	{
		_g_TickTime_? newStart;
		if (Start == null || (other.Start != null && other.Start > Start))
			newStart = other.Start;
		else
			newStart = Start;
		_g_TickTime_? newEnd;
		if (End == null || (other.End != null && other.End < End))
			newEnd = other.End;
		else
			newEnd = End;
		return newStart != null && newEnd != null && newStart > newEnd ? Empty : new _g_TickRangeName_(newStart, newEnd);
	}
	/// <summary>
	/// Creates a new <see cref="_g_TickRangeName_"/> that represents the union of the current range and the specified range.
	/// </summary>
	/// <remarks>The union operation considers null values for the start or end of a range as unbounded.  If both
	/// ranges have null start or end values, the resulting range will also have null for those bounds.</remarks>
	/// <param name="other">The <see cref="_g_TickRangeName_"/> to combine with the current range.</param>
	/// <returns>A new <see cref="_g_TickRangeName_"/> that spans from the earliest start point to the latest end point of the two ranges. If
	/// either range has a null start or end, the resulting range will use the non-null value, if available.</returns>
	public readonly _g_TickRangeName_ Union(_g_TickRangeName_ other)
	{
		_g_TickTime_? newStart;
		if (Start == null || (other.Start != null && other.Start > Start))
			newStart = Start;
		else
			newStart = other.Start;
		_g_TickTime_? newEnd;
		if (End == null || (other.End != null && other.End < End))
			newEnd = End;
		else
			newEnd = other.End;
		return new _g_TickRangeName_(newStart, newEnd);
	}
	/// <summary>
	/// Gets the start and end beats for the current range, using the specified default values if not explicitly
	/// set.
	/// </summary>
	/// <param name="endTime">The default end time to use if the current range does not specify an end value.</param>
	/// <returns>A tuple containing the start and end beats. The start beat is set to the current range's start value if defined;
	/// otherwise, it defaults to 1. The end beat is set to the current range's end value if
	/// defined; otherwise, it defaults to <paramref name="endTime"/>.</returns>
	public readonly (_g_TickTime_ Start, _g_TickTime_ End) GetStartAndEnd(_g_TickTime_ endTime)
			=> (Start is _g_TickTime_ startNotNull ? startNotNull : new(1), End is _g_TickTime_ endNotNull ? endNotNull : endTime);
	/// <summary>
	/// Gets a range that represents an infinite range with no upper or lower bounds.
	/// </summary>
	/// <remarks>This property can be used to represent a range that is unbounded in both directions.</remarks>
	public static _g_TickRangeName_ Infinity => new(null, null);
	/// <summary>
	/// Gets an empty range with no defined start or end values.
	/// </summary>
	public static _g_TickRangeName_ Empty => new(new(), new());
}

