// <auto-generated/>
#nullable enable
namespace _g_tickTimeNamespace_;

/// <summary>
/// A tick.
/// </summary>
public partial struct _g_TickTimeName_ : ITickTime<_g_TickTimeName_>
#if NET7_0_OR_GREATER
	, System.Numerics.IComparisonOperators<_g_TickTimeName_, _g_TickTimeName_, bool>
#endif
{
	internal readonly _g_Chart_? BaseChart => _calculator?.Collection;
	/// <summary>
	/// Gets a value indicating whether the current instance contains no loaded data or associated <see cref="_g_Calculator_"/>.
	/// </summary>
	/// <remarks>The property returns <see langword="true"/> if the <see cref="_g_Calculator_"/> is not set or if none of the data
	/// components are loaded. Use this property to check whether the instance is in an uninitialized or empty state before
	/// performing operations that require loaded data.</remarks>
	[System.Diagnostics.CodeAnalysis.MemberNotNullWhen(false, nameof(_calculator))]
	public readonly partial bool IsEmpty { get; }
	internal static bool MustFromCache { get; } = false;
	/// <summary>
	/// The total number of beats from this moment to the beginning of the <see cref="_g_Chart_"/>.
	/// </summary>
	public partial float Tick { get; }
	/// <summary>
	/// The total amount of time from the beginning of the <see cref="_g_Chart_"/> to this beat.
	/// </summary>
	public partial TimeSpan TimeSpan { get; }
	/// <summary>
	/// The number of beats per minute followed at this moment.
	/// </summary>
	public float Bpm
	{
		get
		{
			if (!_isBPMLoaded)
			{
				_BPM = _calculator?.BeatsPerMinuteOf(this) ?? 0;
				_isBPMLoaded = true;
			}
			return _BPM;
		}
	}
	/// <summary>
	/// Initializes a new instance of the <see cref="_g_TickTimeName_"/> class with default values.
	/// </summary>
	/// <remarks>This constructor sets the initial state of the <see cref="_g_TickTimeName_"/> instance, including default
	/// values for internal fields. The instance is initialized with a beat value of 1, a bar-beat tuple of (1, 1f), a
	/// zero <see cref="System.TimeSpan"/>, and flags indicating that the beat, bar-beat, and time span are loaded.</remarks>
	public _g_TickTimeName_()
	{
		InitDefault();
	}
	[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	partial void InitDefault();
	/// <summary>
	/// Construct an instance without specifying a <see cref="_g_Calculator_"/>.
	/// </summary>
	/// <param name="tick">The total number of beats from this moment to the beginning of the <see cref="_g_Chart_"/>.</param>
	public _g_TickTimeName_(float tick)
	{
		this = default;
		_tick = tick;
		NormalizeTick();
		_isTickLoaded = true;
	}
	/// <summary>
	/// Constructs an instance of RDBeat with the specified time span.
	/// </summary>
	/// <param name="timeSpan">The total amount of time from the start of the <see cref="_g_Chart_"/> to the moment.</param>
	public _g_TickTimeName_(TimeSpan timeSpan)
	{
		this = default;
		_TimeSpan = timeSpan;
		NormalizeTimeSpan();
		_isTimeSpanLoaded = true;
	}
	/// <summary>
	/// Construct an instance with specifying a <see cref="_g_Calculator_"/>.
	/// </summary>
	/// <param name="calculator">Specified <see cref="_g_Calculator_"/>.</param>
	/// <param name="tick">The total number of beats from this moment to the beginning of the <see cref="_g_Chart_"/>.</param>
	public _g_TickTimeName_(_g_Calculator_ calculator, float tick)
	{
		this = new _g_TickTimeName_(tick);
		_calculator = calculator;
	}
	/// <summary>
	/// Construct an instance with specifying a <see cref="_g_Calculator_"/>.
	/// </summary>
	/// <param name="calculator">Specified <see cref="_g_Calculator_"/>.</param>
	/// <param name="timeSpan">The total amount of time from the start of the <see cref="_g_Chart_"/> to the moment</param>
	public _g_TickTimeName_(_g_Calculator_ calculator, TimeSpan timeSpan)
	{
		this = new _g_TickTimeName_(timeSpan);
		_calculator = calculator;
		_tick = _calculator.TimeSpanToTick(timeSpan) - 1f;
	}
	/// <summary>
	/// Construct an instance with specifying a <see cref="_g_Calculator_"/>.
	/// </summary>
	/// <param name="calculator">Specified <see cref="_g_Calculator_"/>.</param>
	/// <param name="beat">Another instance.</param>
	public partial _g_TickTimeName_(_g_Calculator_ calculator, _g_TickTimeName_ beat);
	[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	partial void NormalizeTick();
	partial void NormalizeTimeSpan();
	/// <summary>
	/// Construct a beat of the 1st beat from the <see cref="_g_Calculator_"/>
	/// </summary>
	/// <param name="calculator">Specified <see cref="_g_Calculator_"/>.</param>
	/// <returns>The first beat tied to the <see cref="_g_Chart_"/>.</returns>
	public static _g_TickTimeName_ Default(_g_Calculator_ calculator)
	{
		_g_TickTimeName_ Default = new(calculator, 1f);
		return Default;
	}
	/// <summary>
	/// Determine if two beats come from the same <see cref="_g_Chart_"/>
	/// </summary>
	/// <param name="a">A beat.</param>
	/// <param name="b">Another beat.</param>
	/// <param name="throw">If true, an exception will be thrown when two beats do not come from the same <see cref="_g_Chart_"/>.</param>
	/// <returns><c>true</c> if both beats share the same <see cref="_g_Chart_"/>; otherwise, <c>false</c>.</returns>
	public static bool FromSameChart(_g_TickTimeName_ a, _g_TickTimeName_ b, bool @throw = false) =>
		(a._calculator?.Equals(b._calculator) ?? true)
		|| (@throw ? throw new InvalidOperationException("Beats must come from the same Chart.") : false);
	/// <summary>
	/// Determine if two beats are from the same <see cref="_g_Chart_"/>.
	/// <br />
	/// If any of them does not come from any <see cref="_g_Chart_"/>, it will also return true.
	/// </summary>
	/// <param name="a">A beat.</param>
	/// <param name="b">Another beat.</param>
	/// <param name="throw">If true, an exception will be thrown when two beats do not come from the same <see cref="_g_Chart_"/>.</param>
	/// <returns><c>true</c> if both beats share the same <see cref="_g_Chart_"/> or if either beat is unbound; otherwise, <c>false</c>.</returns>
	public static bool FromSameChartOrNull(_g_TickTimeName_? a, _g_TickTimeName_? b, bool @throw = false) => a?._calculator == null || b?._calculator == null || FromSameChart(a.Value, b.Value, @throw);
	/// <summary>
	/// Determine if two beats are from the same <see cref="_g_Chart_"/>.
	/// </summary>
	/// <param name="b">Another beat.</param>
	/// <param name="throw">If true, an exception will be thrown when two beats do not come from the same <see cref="_g_Chart_"/>.</param>
	/// <returns><c>true</c> if both beats share the same <see cref="_g_Chart_"/>; otherwise, <c>false</c>.</returns>
	[System.Diagnostics.CodeAnalysis.MemberNotNullWhen(true)]
	public readonly bool FromSameChart(_g_TickTimeName_ b, bool @throw = false) => FromSameChart(this, b, @throw);
	/// <summary>
	/// Determine if two beats are from the same <see cref="_g_Chart_"/>.
	/// <br />
	/// If any of them does not come from any <see cref="_g_Chart_"/>, it will also return true.
	/// </summary>
	/// <param name="b">Another beat.</param>
	/// <param name="throw">If true, an exception will be thrown when two beats do not come from the same <see cref="_g_Chart_"/>.</param>
	/// <returns><c>true</c> if both beats share the same <see cref="_g_Chart_"/> or if either beat is unbound; otherwise, <c>false</c>.</returns>
	public readonly bool FromSameChartOrNull(_g_TickTimeName_ b, bool @throw = false) => BaseChart == null || b.BaseChart == null || FromSameChart(b, @throw);
	/// <summary>
	/// Returns a new instance of unbinding the <see cref="_g_Chart_"/>.
	/// </summary>
	/// <returns>A new instance of unbinding the <see cref="_g_Chart_"/>.</returns>
	public readonly _g_TickTimeName_ WithoutLink()
	{
		_g_TickTimeName_ result = this;
		if (result._calculator != null)
			result.Cache();
		result._calculator = null;
		return result;
	}
	/// <summary>
	/// Links the current beat to the specified <see cref="_g_Calculator_"/>, enabling it to be used for beat calculations.
	/// </summary>
	/// <remarks>If the current beat is already linked to a <see cref="_g_Calculator_"/>, providing a different
	/// <see cref="_g_Calculator_"/> will result in an exception. This method does not modify the original instance if it is already linked
	/// to the specified <see cref="_g_Calculator_"/>.</remarks>
	/// <param name="calculator">The <see cref="_g_Calculator_"/> instance to associate with this beat. This parameter cannot be null.</param>
	/// <returns>The current <see cref="_g_TickTimeName_"/> instance with the linked <see cref="_g_Calculator_"/>.</returns>
	/// <exception cref="InvalidOperationException">Thrown if the beat is already linked to a different <see cref="_g_Calculator_"/>.</exception>
	public readonly _g_TickTimeName_ WithLink(_g_Calculator_ calculator)
	{
		_g_TickTimeName_ result = this;
		if (result._calculator == null)
			result._calculator = calculator;
		else if (!ReferenceEquals(result._calculator, calculator))
			throw new InvalidOperationException("The beat is already linked to another _g_chartSymbolName_.");
		return result;
	}
	/// <summary>
	/// Returns a new RDBeat instance with the specified <see cref="_g_Calculator_"/> assigned if the current instance does not already have
	/// a <see cref="_g_Calculator_"/>.
	/// </summary>
	/// <remarks>Use this method to ensure that an RDBeat instance has an associated <see cref="_g_Calculator_"/> without overwriting
	/// an existing one.</remarks>
	/// <param name="calculator">The <see cref="_g_Calculator_"/> to assign if the current instance's <see cref="_g_Calculator_"/> is null.</param>
	/// <returns>An RDBeat instance with the calculator set to the specified value if it was previously null; otherwise, the current
	/// instance.</returns>
	public readonly _g_TickTimeName_ WithLinkIfNull(_g_Calculator_ calculator)
	{
		_g_TickTimeName_ result = this;
		if (result._calculator == null)
			result._calculator = calculator;
		return result;
	}
	/// <summary>
	/// Creates a new RDBeat instance that is linked to the specified <see cref="_g_Chart_"/>.
	/// </summary>
	/// <param name="chart">The <see cref="_g_Chart_"/> to which the new RDBeat instance will be linked. Cannot be null.</param>
	/// <returns>A new RDBeat instance associated with the provided <see cref="_g_Chart_"/>.</returns>
	[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	public readonly _g_TickTimeName_ WithLink(_g_Chart_ chart) => WithLink(chart.Calculator);
	/// <summary>
	/// Returns a new RDBeat instance that is linked to the specified <see cref="_g_Chart_"/>'s <see cref="_g_Calculator_"/> if it is not already linked.
	/// </summary>
	/// <param name="chart">The <see cref="_g_Chart_"/> whose <see cref="_g_Calculator_"/> will be used to link the RDBeat instance. This parameter must not be null.</param>
	/// <returns>A new RDBeat instance linked to the <see cref="_g_Calculator_"/> of the specified <see cref="_g_Chart_"/>.</returns>
	[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	public readonly _g_TickTimeName_ WithLinkIfNull(_g_Chart_ chart) => WithLinkIfNull(chart.Calculator);
	[System.Diagnostics.CodeAnalysis.MemberNotNull(nameof(_calculator))]
	[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	internal readonly void IfNullThrowException()
	{
		if (IsEmpty)
		{
			throw new InvalidRDBeatException();
		}
	}
	internal partial void ResetBPM();
	/// <summary>
	/// Refresh the cache.
	/// </summary>
	public partial void ResetCache();
	/// <summary>
	/// Caches the current state of the beat by accessing its properties.
	/// </summary>
	/// <exception cref="InvalidRDBeatException">Thrown when the beat cannot be calculated.</exception>
	public partial void Cache();
	[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	private static partial int CompareInternal(_g_TickTimeName_ left, _g_TickTimeName_ right);
	/// <summary>
	/// Adds a specified number of beats to the current beat and caches the result.
	/// </summary>
	/// <param name="left">The current beat instance.</param>
	/// <param name="right">The number of beats to add.</param>
	/// <param name="result">The result beat instance.</param>
	[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	private static partial void AddTickAndCache(_g_TickTimeName_ left, float right, ref _g_TickTimeName_ result);
	/// <summary>
	/// Adds a specified <see cref="TimeSpan"/> to the current beat and caches the result.
	/// </summary>
	/// <param name="left">The current beat instance.</param>
	/// <param name="right">The time span to add.</param>
	/// <param name="result">The result beat instance.</param>
	[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	private static partial void AddTimeSpanAndCache(_g_TickTimeName_ left, TimeSpan right, ref _g_TickTimeName_ result);
	/// <summary>
	/// Subtracts a specified number of beats from the current beat and caches the result.
	/// </summary>
	/// <param name="left">The current beat instance.</param>
	/// <param name="right">The number of beats to subtract.</param>
	/// <param name="result">The result beat instance.</param>
	[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	private static partial void SubstractTickAndCache(_g_TickTimeName_ left, float right, ref _g_TickTimeName_ result);
	/// <summary>
	/// Subtracts a specified <see cref="TimeSpan"/> from the current beat and caches the result.
	/// </summary>
	/// <param name="left">The current beat instance.</param>
	/// <param name="right">The time span to subtract.</param>
	/// <param name="result">The result beat instance.</param>
	[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	private static partial void SubstractTimeSpanAndCache(_g_TickTimeName_ left, TimeSpan right, ref _g_TickTimeName_ result);
	/// <inheritdoc/>
	public static _g_TickTimeName_ operator +(_g_TickTimeName_ left, float right)
	{
		if (right == 0) return left;
		_g_TickTimeName_ result = new();
		if (!left.IsEmpty)
			result = new _g_TickTimeName_(left._calculator!, left.Tick + right);
		else
		{
			AddTickAndCache(left, right, ref result);
			result._isTimeSpanLoaded = false;
		}
		return result;
	}
	/// <inheritdoc/>
	public static _g_TickTimeName_ operator +(_g_TickTimeName_ left, TimeSpan right)
	{
		if (right == TimeSpan.Zero) return left;
		_g_TickTimeName_ result = new();
		if (!left.IsEmpty)
			result = new _g_TickTimeName_(left._calculator!, left.TimeSpan + right);
		else
		{
			AddTimeSpanAndCache(left, right, ref result);
			result._isTickLoaded = false;
		}
		return result;
	}
	/// <inheritdoc/>
	public static _g_TickTimeName_ operator -(_g_TickTimeName_ left, float right)
	{
		if (right == 0f) return left;
		_g_TickTimeName_ result = new();
		if (!left.IsEmpty)
			result = new _g_TickTimeName_(left._calculator!, left.Tick - right);
		else
		{
			SubstractTickAndCache(left, right, ref result);
			result._isTimeSpanLoaded = false;
		}
		return result;
	}
	/// <inheritdoc/>
	public static _g_TickTimeName_ operator -(_g_TickTimeName_ left, TimeSpan right)
	{
		if (right == TimeSpan.Zero) return left;
		_g_TickTimeName_ result = new();
		if (!left.IsEmpty)
			result = new _g_TickTimeName_(left._calculator!, left.TimeSpan - right);
		else
		{
			SubstractTimeSpanAndCache(left, right, ref result);
			result._isTickLoaded = false;
		}
		return result;
	}
	/// <inheritdoc/>
	public static bool operator >(_g_TickTimeName_ a, _g_TickTimeName_ b) => CompareInternal(a, b) > 0;
	/// <inheritdoc/>
	public static bool operator <(_g_TickTimeName_ a, _g_TickTimeName_ b) => CompareInternal(a, b) < 0;
	/// <inheritdoc/>
	public static bool operator >=(_g_TickTimeName_ a, _g_TickTimeName_ b) => CompareInternal(a, b) >= 0;
	/// <inheritdoc/>
	public static bool operator <=(_g_TickTimeName_ a, _g_TickTimeName_ b) => CompareInternal(a, b) <= 0;
	/// <inheritdoc/>
	public static bool operator ==(_g_TickTimeName_ a, _g_TickTimeName_ b) => CompareInternal(a, b) == 0;
	/// <inheritdoc/>
	public static bool operator !=(_g_TickTimeName_ a, _g_TickTimeName_ b) => CompareInternal(a, b) != 0;
	/// <inheritdoc/>
	public override partial string ToString();
	/// <inheritdoc/>
	public readonly override bool Equals([System.Diagnostics.CodeAnalysis.NotNullWhen(true)] object? obj) => obj is _g_TickTimeName_ e && Equals(e);
	/// <inheritdoc/>
	public static partial _g_TickTimeName_ Min(_g_TickTimeName_ left, _g_TickTimeName_ right);
	/// <inheritdoc/>
	public static partial _g_TickTimeName_ Max(_g_TickTimeName_ left, _g_TickTimeName_ right);
	/// <inheritdoc/>
	public readonly bool Equals(_g_TickTimeName_ other) => this == other;
	/// <inheritdoc/>
#if NETSTANDARD
	public override int GetHashCode()
	{
		int hash = 17;
		hash = hash * 31 + (_calculator?.GetHashCode() ?? 0);
		hash = hash * 31 + _isTickLoaded.GetHashCode();
		hash = hash * 31 + _isTimeSpanLoaded.GetHashCode();
		hash = hash * 31 + _tick.GetHashCode();
		hash = hash * 31 + _TimeSpan.GetHashCode();
		return hash;
	}
#else
	public override int GetHashCode() => HashCode.Combine(Tick, BaseChart);
#endif
	/// <inheritdoc/>
	public readonly int CompareTo(_g_TickTimeName_ other) => this > other ? 1 : this == other ? 0 : -1;

	internal _g_Calculator_? _calculator;
	private bool _isTickLoaded;
	private bool _isTimeSpanLoaded;
	private bool _isBPMLoaded;
	private float _tick;
	private TimeSpan _TimeSpan;
	private float _BPM;
}
