<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>RhythmBase</RootNamespace>
		<AssemblyName>RhythmBase</AssemblyName>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<Title>RhythmBase</Title>
		<Version>1.3.11-alpha9</Version>
		<Authors>obugs</Authors>
		<Description>A package that can be used to help with the development of support tools for the rhythm game levels.</Description>
		<PackageProjectUrl>https://github.com/RDCN-Community-Developers/RhythmToolkit</PackageProjectUrl>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageTags>Rhythm Game</PackageTags>
		<PackageReleaseNotes>VERSION.md</PackageReleaseNotes>
		<PackageIcon>RhythmBase_logo_small.png</PackageIcon>
		<RepositoryUrl>https://github.com/RDCN-Community-Developers/RhythmToolkit.git</RepositoryUrl>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<LangVersion>Preview</LangVersion>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<IsAotCompatible>true</IsAotCompatible>
		<VerifyReferenceAotCompatibility>true</VerifyReferenceAotCompatibility>
		<EmitCompilerGeneratedFiles Condition="'$(Configuration)'=='Debug'">true</EmitCompilerGeneratedFiles>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="System.Text.Json" Version="9.0.0" />
		<ProjectReference Include="../RhythmBase.Generator/RhythmBase.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
		<None Include="../RhythmBase.Generator/bin/$(Configuration)/netstandard2.0/RhythmBase.Generator.dll" Pack="True" Visible="False" PackagePath="analyzers/dotnet/cs/RhythmBase.Generator.dll" CopyToOutputDirectory="PreserveNewest" />
		<None Include="../CONTRIBUTION.zh-cn.md" Pack="False" />
		<None Include="../README.md;../README.zh-cn.md;../VERSION.md;../VERSION.zh-cn.md;../RhythmBase_logo_small.png;../RhythmBase_logo.png;../RhythmBase_logo_clean.png;../RhythmBase_banner.png;../RhythmBase_banner_clean.png;../LICENSE.txt;" Pack="True" PackagePath="/" />
		<Compile Include="../DotnetCompatibility.cs"></Compile>
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Global\Config\" />
	</ItemGroup>
</Project>
