Namespace Settings
    ''' <summary>
    ''' Level import settings.
    ''' </summary>
    Public Enum ActionOnUnreadableEvents
        ''' <summary>
        ''' Stores unreadable events in <see cref="LevelReadOrWriteSettings.UnreadableEvents"/> for restoration.
        ''' </summary>
        Store
        ''' <summary>
        ''' An exception will be thrown.
        ''' </summary>
        ThrowException
    End Enum
    Public Class LevelReadOrWriteSettings
        ''' <summary>
        ''' Enable resource preloading. This may grow read times. 
        ''' Defaults to <see langword="false"/>.
        ''' </summary>
        Public Property PreloadAssets As Boolean = False
        ''' <summary>
        ''' Uses the ID from the original level instead of being generated by the program. 
        ''' Defaults to <see langword="true"/>.
        ''' </summary>
        Public Property UsingIdFromFile As Boolean = True
        ''' <summary>
        ''' Action on unreadable events.
        ''' Defaults to <see cref="ActionOnUnreadableEvents.ThrowException"/>.
        ''' </summary>
        Public Property UnreadableEventAction As ActionOnUnreadableEvents = ActionOnUnreadableEvents.ThrowException
        ''' <summary>
        ''' Stores unreadable event data when the <see cref="LevelReadOrWriteSettings.UnreadableEventAction"/> is <see langword="true"/>.
        ''' </summary>
        ''' <returns></returns>
        Public Property UnreadableEvents As New List(Of Newtonsoft.Json.Linq.JObject)
        ''' <summary>
        ''' Whether to overwrite the source file.
        ''' If <see langword="false"/> and the export path is the same as the source path, an exception will be thrown.
        ''' Defaults to <see langword="false"/>.
        ''' </summary>
        Public Property OverWrite As Boolean = False
        ''' <summary>
        ''' Use indentation. 
        ''' Defaults to <see langword="true"/>.
        ''' </summary>
        Public Property Indented As Boolean = True
    End Class
    Public Class SpriteReadOrWriteSettings
        ''' <summary>
        ''' Whether to overwrite the source file.
        ''' If <see langword="false"/> and the export path is the same as the source path, an exception will be thrown.
        ''' Defaults to <see langword="false"/>.
        ''' </summary>
        Public Property OverWrite As Boolean = False
        ''' <summary>
        ''' Use the indent and align expressions property.
        ''' Defaults to <see langword="true"/>.
        ''' </summary>
        Public Property Indented As Boolean = True
        ''' <summary>
        ''' Ignore all null values.
        ''' </summary>
        ''' Defaults to <see langword="false"/>.
        Public Property IgnoreNullValue As Boolean = False
        ''' <summary>
        ''' Export the image file at the same time as the export.
        ''' </summary>
        ''' Defaults to <see langword="false"/>.
        Public Property WithImage As Boolean = False
    End Class
End Namespace