using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;

namespace RhythmBase.Generator;

public partial class ConverterGenerator
{
	private static string ReplaceVariableWithName(string template)
	{
		return template
			.Replace("$&", "value")
			.Replace("$r", "_rs")
			.Replace("$w", "_ws");
	}
	private static void GenerateEventTypeRegistry(IncrementalGeneratorInitializationContext context, IncrementalValueProvider<(((string?, List<Diagnostic>), Compilation), EventTypeRegistryGenerationInfo[])> registryInfo)
	{
		context.RegisterSourceOutput(registryInfo, GenerateEventTypeUtils);
	}
	private static void GenerateEnumConverter(IncrementalGeneratorInitializationContext context, IncrementalValueProvider<(string?, List<Diagnostic>)> registryInfo)
	{
		var enums1 = context.SyntaxProvider.ForAttributeWithMetadataName(
			JsonEnumCastingAttrName,
			predicate: static (node, _) => true,
			transform: static (context, _) =>
			{
				var attr = context.Attributes[0];
				var enumType = attr.ConstructorArguments[0].Value as INamedTypeSymbol;
				var pascalCase = attr.ConstructorArguments[1].Value as bool? ?? true;
				var members = enumType.GetMembers().OfType<IFieldSymbol>().Where(m => m.ConstantValue is not null).ToArray();
				return (enumType, pascalCase, members);
			}).Collect();
		var enums2 = context.SyntaxProvider.ForAttributeWithMetadataName(
				JsonEnumAttrName,
				predicate: (s, e) => s is EnumDeclarationSyntax enumDeclaration,
				transform: (ctx, e) =>
				{
					if (ctx.TargetNode is not EnumDeclarationSyntax enumDeclaration)
						return default;
					INamedTypeSymbol? symbol = ctx.SemanticModel.GetDeclaredSymbol(enumDeclaration);
					if (symbol is null)
						return default;
					var pascalCase = ctx.Attributes[0].ConstructorArguments[0].Value as bool? ?? true;
					var members = symbol.GetMembers().OfType<IFieldSymbol>().ToArray();
					return (symbol, pascalCase, members);
				}
			).Collect();
		context.RegisterSourceOutput(registryInfo.Combine(enums1.Combine(enums2)), (spc, registryInfoAndEnumSymbols) =>
		{
			((var registryId, var diagnostics), var enumSymbolsAll) = registryInfoAndEnumSymbols;
			foreach (var diag in diagnostics)
				spc.ReportDiagnostic(diag);
			(var enums1, var enums2) = enumSymbolsAll;
			List<(INamedTypeSymbol Type, bool PascalCase, IFieldSymbol[] Members)> enums = new();
			foreach (var (enumType, pascalCase, members) in enums1)
			{
				enums.Add((enumType, pascalCase, members));
			}
			foreach (var (enumType, pascalCase, members) in enums2)
			{
				enums.Add((enumType, pascalCase, members));
			}
			if (string.IsNullOrEmpty(registryId))
				return;
			StringBuilder sb1 = new();
			StringBuilder sb2 = new();
			sb1.AppendLine($$"""
					// <auto-generated/>
					#nullable enable
						using System;
						using System.Runtime.CompilerServices;
						using System.Text.Json;
					
					namespace RhythmBase.{{registryId}}.Serialization;
					/// <summary>
					/// Provides extension methods for converting enum values to and from their JSON string representations.
					/// </summary>
					public static class EnumConverterExtensions
						{
							/// <summary>
							/// Provides extension methods for converting enums to and from string representations.
							/// </summary>
							extension(RhythmBase.Global.Serialization.EnumConverter)
							{
					""");
			foreach (var e in enums.OrderBy(i => i.Type.Name))
			{
				static string GetStringName(IFieldSymbol symbol, bool pascalCase)
				{
					if (symbol.GetAttributes().FirstOrDefault(a => IsAttribute(a, JsonAliasAttrName) && a.ConstructorArguments.Length == 1)?.ConstructorArguments[0].Value is not string alias)
						return pascalCase ? symbol.Name : ToLowerCamelCase(symbol.Name);
					else
						return alias;
				}
				bool pascalCase = e.PascalCase;
				string fullName = e.Type.ToDisplayString();

				// TryParse(string)
				sb1.AppendLine($$"""
							/// <summary>
							/// Attempts to parse the specified string value to a <see cref="{{fullName}}"/> enum value.
							/// </summary>
							/// <param name="value">The string representation of the enum value.</param>
							/// <param name="result">When this method returns, contains the parsed <see cref="{{fullName}}"/> value if parsing succeeded; otherwise, the default value.</param>
							/// <returns><c>true</c> if parsing succeeded; otherwise, <c>false</c>.</returns>
							[MethodImpl(MethodImplOptions.AggressiveInlining)]
							public static bool TryParse(string? value, out {{fullName}} result)
							{
								switch(value) {
					""");
				foreach (var field in e.Members.OrderBy(i => i.Name))
				{
					sb1.AppendLine($$"""
									case "{{GetStringName(field, pascalCase)}}":
										result = {{field.ToDisplayString()}}; return true;
					""");
				}
				sb1.AppendLine("""
									default:
										result = default; return false;
								}
							}
					
					""");
				sb1.AppendLine();

				// TryParse(ReadOnlySpan<byte>)
				sb1.AppendLine($$"""
							/// <summary>
							/// Attempts to parse the specified UTF-8 byte span to a <see cref="{{fullName}}"/> enum value.
							/// </summary>
							/// <param name="value">The UTF-8 byte span representing the enum value.</param>
							/// <param name="result">When this method returns, contains the parsed <see cref="{{fullName}}"/> value if parsing succeeded; otherwise, the default value.</param>
							/// <returns><c>true</c> if parsing succeeded; otherwise, <c>false</c>.</returns>
							[MethodImpl(MethodImplOptions.AggressiveInlining)]
							public static bool TryParse(ReadOnlySpan<byte> value, out {{fullName}} result)
							{
					""");
				bool isFirst = true;
				foreach (var field in e.Members.OrderBy(i => i.Name))
				{
					sb1.AppendLine($$"""
								{{(isFirst ? "" : "else ")}}if (value.SequenceEqual("{{GetStringName(field, pascalCase)}}"u8))
								{
									result = {{field.ToDisplayString()}};
									return true;
								}
					""");
					isFirst = false;
				}
				sb1.AppendLine("""
								else
								{
									result = default;
									return false;
								}
							}

					""");

				// TryParse(ref Utf8JsonReader)
				sb1.AppendLine($$"""
							/// <summary>
							/// Attempts to parse the current JSON token value to a <see cref="{{fullName}}"/> enum value.
							/// Works with <see cref="System.Buffers.ReadOnlySequence{T}"/>-backed readers without allocating.
							/// </summary>
							/// <param name="reader">The JSON reader positioned at a string token.</param>
							/// <param name="result">When this method returns, contains the parsed <see cref="{{fullName}}"/> value if parsing succeeded; otherwise, the default value.</param>
							/// <returns><c>true</c> if parsing succeeded; otherwise, <c>false</c>.</returns>
							[MethodImpl(MethodImplOptions.AggressiveInlining)]
							public static bool TryParse(ref Utf8JsonReader reader, out {{fullName}} result)
							{
					""");
				isFirst = true;
				foreach (var field in e.Members.OrderBy(i => i.Name))
				{
					sb1.AppendLine($$"""
								{{(isFirst ? "" : "else ")}}if (reader.ValueTextEquals("{{GetStringName(field, pascalCase)}}"u8))
								{
									result = {{field.ToDisplayString()}};
									return true;
								}
					""");
					isFirst = false;
				}
				sb1.AppendLine("""
								else
								{
									result = default;
									return false;
								}
							}

					""");

				// ToEnumString
				sb2.AppendLine($$"""
						/// <summary>
						/// Converts the <see cref="{{fullName}}"/> enum value to its string representation.
						/// </summary>
						/// <param name="value">The enum value to convert.</param>
						/// <returns>The string representation of the enum value.</returns>
						[MethodImpl(MethodImplOptions.AggressiveInlining)]
						public static string ToEnumString(this {{fullName}} value) => value switch
						{
					""");
				foreach (var field in e.Members.OrderBy(i => i.Name))
				{
					sb2.AppendLine($"""
								{field.ToDisplayString()} => "{GetStringName(field, pascalCase)}",
					""");
				}
				sb2.AppendLine("""
								_ => value.ToString(),
						};
					""");


				// ToEnumUtf8String
				sb2.AppendLine($$"""
						/// <summary>
						/// Converts the <see cref="{{fullName}}"/> enum value to its UTF-8 string representation.
						/// </summary>
						/// <param name="value">The enum value to convert.</param>
						/// <returns>The string representation of the enum value.</returns>
						[MethodImpl(MethodImplOptions.AggressiveInlining)]
						public static ReadOnlySpan<byte> ToEnumUtf8String(this {{fullName}} value) => value switch
						{
					""");
				foreach (var field in e.Members.OrderBy(i => i.Name))
				{
					sb2.AppendLine($"""
								{field.ToDisplayString()} => "{GetStringName(field, pascalCase)}"u8,
					""");
				}
				sb2.AppendLine("""
								_ => System.Text.Encoding.UTF8.GetBytes(value.ToString()),
						};
					""");
			}
			sb1.AppendLine($$"""
						}
					{{sb2.ToString()}}
					}
					""");
			spc.AddSource($"EnumConverters.{registryId}.g.cs", sb1.ToString());
		});
	}
	private static IEnumerable<INamedTypeSymbol> GetDerivedTypes(INamedTypeSymbol baseType, Compilation compilation, bool includeReferences = false)
	{
		foreach (var t in GetAllTypes(compilation.GlobalNamespace))
			if (IsDerivedFrom(t, baseType))
				yield return t;
		if (!includeReferences) yield break;
		foreach (var asm in compilation.SourceModule.ReferencedAssemblySymbols)
			foreach (var t in GetAllTypes(asm.GlobalNamespace))
				if (IsDerivedFrom(t, baseType))
					yield return t;
	}
	private static bool IsDerivedFrom(INamedTypeSymbol? candidate, INamedTypeSymbol? baseType)
	{
		if (SymbolEqualityComparer.Default.Equals(candidate, baseType))
			return true;
		if (baseType?.TypeKind == TypeKind.Interface)
			return candidate?.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, baseType)) ?? false;
		for (var current = candidate?.BaseType;
				current != null && current.SpecialType != SpecialType.System_Object;
				current = current.BaseType)
		{
			if (SymbolEqualityComparer.Default.Equals(current, baseType))
				return true;
		}
		return false;
	}
	private static IEnumerable<INamedTypeSymbol> GetAllTypes(INamespaceSymbol namespaceSymbol)
	{
		foreach (var member in namespaceSymbol.GetMembers())
		{
			if (member is INamespaceSymbol nestedNS)
				foreach (var type in GetAllTypes(nestedNS))
					yield return type;
			else if (member is INamedTypeSymbol namedType)
			{
				yield return namedType;
				foreach (var nested in namedType.GetTypeMembers())
					yield return nested;
			}
		}
	}
	private static IEnumerable<INamedTypeSymbol> GetAllTypes(IAssemblySymbol assemblySymbol)
	{
		foreach (var module in assemblySymbol.Modules)
			foreach (var type in GetAllTypes(module.GlobalNamespace))
				yield return type;
	}

	private void GenerateTypeConverterRegistry(IncrementalGeneratorInitializationContext context, IncrementalValueProvider<((string?, List<Diagnostic>) Left, (ITypeSymbol, INamedTypeSymbol)[] Right)> incrementalValueProvider)
	{
		context.RegisterSourceOutput(incrementalValueProvider, (ctx, data) =>
	{
		var ((left, diagnostics), right) = data;
		foreach (var diag in diagnostics)
			ctx.ReportDiagnostic(diag);
		if (string.IsNullOrEmpty(left) || left == CoreNs)
			return;
		StringBuilder sb = new();
		sb.AppendLine($$"""
						// <auto-generated/>
						#nullable enable
						using System.Text.Json;
						using System.Text.Json.Serialization;
						using RhythmBase.Global.Serialization;

						namespace RhythmBase.{{left}}.Serialization;

						internal static partial class TypeConverterRegistry
						{
							private static class ConverterCache<T>
							{
								public static JsonConverter? Converter;
							}
							static TypeConverterRegistry()
							{
						""");
		foreach (var pair in right)
		{
			sb.AppendLine($$"""
								ConverterCache<{{pair.Item1.ToDisplayString()}}>.Converter = new {{pair.Item2.ToDisplayString()}}();
						""");
		}
		sb.AppendLine("""
							}
							public static T Read<T>(ref Utf8JsonReader reader, MetadataJsonSerializerOptions options)
							{
								if (ConverterCache<T>.Converter is MetadataJsonConverter<T> c1)
									return c1.Read(ref reader, typeof(T), options) ?? default!;
								if (ConverterCache<T>.Converter is JsonConverter<T> c2)
									return c2.Read(ref reader, typeof(T), options.JsonSerializerOptions) ?? default!;
								else
						#if DEBUG
									throw new NotImplementedException($"No converter found for type {typeof(T)}.");
						#else
									return default!;
						#endif
							}
							public static void Write<T>(Utf8JsonWriter writer, T value, MetadataJsonSerializerOptions options)
							{
								if (ConverterCache<T>.Converter is MetadataJsonConverter<T> c1)
									c1.Write(writer, value, options);
								else if (ConverterCache<T>.Converter is JsonConverter<T> c2)
									c2.Write(writer, value, options.JsonSerializerOptions);
								else
						#if DEBUG
									throw new NotImplementedException($"No converter found for type {typeof(T)}.");
						#else
									writer.WriteNullValue();
						#endif
							}
						}
						""");
		ctx.AddSource($"TypeConverterRegistry.{left}.g.cs", sb.ToString());
	});
	}
	private static ITypeSymbol UnwarpNullable(ITypeSymbol type)
	{
		if (type.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T
			&& type is INamedTypeSymbol namedType
			&& namedType.TypeArguments.Length == 1)
			return namedType.TypeArguments[0];
		return type.WithNullableAnnotation(NullableAnnotation.NotAnnotated);
	}
	private void GenerateReadBody(Compilation compilation, StringBuilder sb, ClassGenCvtrInfo info, (ITypeSymbol, INamedTypeSymbol)[] classGenMap)
	{
		//sb.AppendLine("/*\n");


		sb.AppendLine("""
								if (base.Read(ref reader, ref value, options))
									return true;
						""");
		int index = 0;
		foreach (var prop in info.Properties.OrderBy(i => i.Property.Name))
		{
			var attrs = prop.Property.GetAttributes();
			var aliasAttrSmp = compilation.GetTypeByMetadataName(JsonAliasAttrName);
			var condAttrSmp = compilation.GetTypeByMetadataName(JsonConditionAttrName);
			var ignoreAttrSmp = compilation.GetTypeByMetadataName(JsonIgnoreAttrName);
			var jsonCvtrAttrSmp = compilation.GetTypeByMetadataName(JsonConverterAttrName);
			var timeCvtrAttrSmp = compilation.GetTypeByMetadataName(JsonTimeAttrName);
			var dftCvtrAttrSmp = compilation.GetTypeByMetadataName(JsonDefaultSerializerAttrName);
			var jsonEnumAttrSmp = compilation.GetTypeByMetadataName(JsonEnumAttrName);
			var jsonFlattenAttrSmp = compilation.GetTypeByMetadataName(JsonFlattenAttrName);

			bool shouldGenerate = GetShouldGenerate(prop, compilation);
			bool isNullable = prop.Property.Type.NullableAnnotation == NullableAnnotation.Annotated;
			if (shouldGenerate)
			{

				string alias = attrs.FirstOrDefault(i => SymbolEqualityComparer.Default.Equals(i.AttributeClass, aliasAttrSmp) && i.ConstructorArguments.Length == 1)?.ConstructorArguments[0].Value as string
						?? ToLowerCamelCase(prop.Property.ToDisplayParts().Last().ToString());
				string? condition = attrs.FirstOrDefault(i => SymbolEqualityComparer.Default.Equals(i.AttributeClass, condAttrSmp) && i.ConstructorArguments.Length == 1)?.ConstructorArguments[0].Value as string;
				INamedTypeSymbol? jsonCvtr = attrs.FirstOrDefault(i => SymbolEqualityComparer.Default.Equals(i.AttributeClass, jsonCvtrAttrSmp) && i.ConstructorArguments.Length == 1)?.ConstructorArguments[0].Value as INamedTypeSymbol;
				int? timeEnum = attrs.FirstOrDefault(i => SymbolEqualityComparer.Default.Equals(i.AttributeClass, timeCvtrAttrSmp) && i.ConstructorArguments.Length == 1)?.ConstructorArguments[0].Value as int?;

				string valueAccess = $"value.{prop.Property.ToDisplayParts().Last()}";
				{
					sb.AppendLine($$"""{{(index == 0 ? "" : "else ")}}if (reader.ValueTextEquals("{{alias}}"u8) && reader.Read())""");
					if (isNullable)
						sb.AppendLine($$"""
							{ if (reader.TokenType == JsonTokenType.Null) value.{{prop.Property.ToDisplayParts().Last()}} = null;
								else
					""");

					var type = UnwarpNullable(prop.Property.Type);

					GenerateReadProperty(new GeneratePropertyInfo(compilation, sb, classGenMap, index, attrs, dftCvtrAttrSmp, jsonEnumAttrSmp, isNullable, jsonCvtr, timeEnum, valueAccess, type));
					if (isNullable)
						sb.Append("}");
					sb.AppendLine();
				}
			}
			// JsonFlatten: 展平子属性到当前层级
			AttributeData[] jsonFlattenAttrs = attrs.Where(i => SymbolEqualityComparer.Default.Equals(i.AttributeClass, jsonFlattenAttrSmp)).ToArray();
			if (jsonFlattenAttrs.Length > 0)
			{
				var parentType = UnwarpNullable(prop.Property.Type);
				bool parentIsValueType = parentType.TypeKind == TypeKind.Struct;
				foreach (var attr in jsonFlattenAttrs)
				{
					string subPropName = attr.ConstructorArguments[0].Value is string s ? s : throw new InvalidOperationException("Invalid JsonFlatten attribute: missing property name.");
					string aliasName = attr.ConstructorArguments[1].Value is string s2 ? s2 : ToLowerCamelCase(subPropName);
					int mode = attr.ConstructorArguments.Length >= 3 && attr.ConstructorArguments[2].Value is int m ? m : 3; // ReadWrite = 3
					if ((mode & 1) == 0) continue; // bit 0 = ReadOnly

					var subProp = parentType.GetMembers().FirstOrDefault(m => m.Name == subPropName) as IPropertySymbol;
					if (subProp is null) continue;

					bool subIsNullable = subProp.Type.NullableAnnotation == NullableAnnotation.Annotated;
					var subType = UnwarpNullable(subProp.Type);
					string parentAccess = $"value.{prop.Property.Name}";

					sb.AppendLine($$"""else if (reader.ValueTextEquals("{{aliasName}}"u8) && reader.Read())""");

					string flatValueAccess;
					if (parentIsValueType)
					{
						if (isNullable)
						{
							sb.AppendLine($$"""
								{ {{parentAccess}} ??= new();
								  var __flatParent = {{parentAccess}}.Value;
							""");
						}
						else
						{
							sb.AppendLine($$"""
								{ var __flatParent = {{parentAccess}};
							""");
						}
						flatValueAccess = $"__flatParent.{subPropName}";
					}
					else
					{
						if (isNullable)
						{
							sb.AppendLine($$"""
								{ {{parentAccess}} ??= new();
							""");
						}
						else
						{
							sb.AppendLine("{");
						}
						flatValueAccess = $"{parentAccess}.{subPropName}";
					}

					if (subIsNullable)
					{
						sb.AppendLine($$"""
							if (reader.TokenType == JsonTokenType.Null) {{flatValueAccess}} = null;
							else
						""");
					}

					// 查找子属性上的 JsonAlias / JsonTime / JsonConverter / JsonDefaultSerializer
					var subAttrs = subProp.GetAttributes();
					INamedTypeSymbol? subJsonCvtr = subAttrs.FirstOrDefault(i => SymbolEqualityComparer.Default.Equals(i.AttributeClass, jsonCvtrAttrSmp) && i.ConstructorArguments.Length == 1)?.ConstructorArguments[0].Value as INamedTypeSymbol;
					int? subTimeEnum = subAttrs.FirstOrDefault(i => SymbolEqualityComparer.Default.Equals(i.AttributeClass, timeCvtrAttrSmp) && i.ConstructorArguments.Length == 1)?.ConstructorArguments[0].Value as int?;
					GenerateReadProperty(new GeneratePropertyInfo(compilation, sb, classGenMap, index, subAttrs, dftCvtrAttrSmp, jsonEnumAttrSmp, subIsNullable, subJsonCvtr, subTimeEnum, flatValueAccess, subType));
					if (parentIsValueType)
					{
						sb.AppendLine($$"""  {{parentAccess}} = __flatParent;""");
					}
					sb.AppendLine("}");
				}
			}

			index++;
		}
		sb.AppendLine("""
								else return false;
								return true;
						""");
	}

	private static bool GetShouldGenerate(PropertyGenerateConverterInfo prop, Compilation compilation)
	{
		var attrs = prop.Property.GetAttributes();
		var aliasAttrSmp = compilation.GetTypeByMetadataName(JsonAliasAttrName);
		var condAttrSmp = compilation.GetTypeByMetadataName(JsonConditionAttrName);
		var ignoreAttrSmp = compilation.GetTypeByMetadataName(JsonIgnoreAttrName);
		return prop.Property.SetMethod is not null &&
						prop.Property.ExplicitInterfaceImplementations.Length == 0 && // 不是显式接口实现或继承
						(
							(
								prop.Property.DeclaredAccessibility.HasFlag(Accessibility.Public) || // 公开属性，或
								attrs.FirstOrDefault(i => SymbolEqualityComparer.Default.Equals(i.AttributeClass, aliasAttrSmp)) is not null // 有 JsonAlias 属性
							) &&
							attrs.FirstOrDefault(i => SymbolEqualityComparer.Default.Equals(i.AttributeClass, ignoreAttrSmp)) is null // 没有 JsonIgnore 属性
						) &&
						(attrs.FirstOrDefault(i => SymbolEqualityComparer.Default.Equals(i.AttributeClass, condAttrSmp)) is not AttributeData i || i.ConstructorArguments.Length == 1 &&
							i.ConstructorArguments[0].Value is string s &&
							s != "false") // 没有 JsonCondition(false) 属性
						;
	}

	private class GeneratePropertyInfo
	{
		public GeneratePropertyInfo(Compilation compilation, StringBuilder sb, (ITypeSymbol, INamedTypeSymbol)[] classGenMap, int index, ImmutableArray<AttributeData> attrs, INamedTypeSymbol? dftCvtrAttrSmp, INamedTypeSymbol? jsonEnumAttrSmp, bool isNullable, INamedTypeSymbol? jsonCvtr, int? timeEnum, string valueAccess, ITypeSymbol type)
		{
			Compilation = compilation;
			StringBuilder = sb;
			ClassGenMap = classGenMap;
			Index = index;
			Attrs = attrs;
			DftCvtrAttrSmp = dftCvtrAttrSmp;
			JsonEnumAttrSmp = jsonEnumAttrSmp;
			IsNullable = isNullable;
			JsonCvtr = jsonCvtr;
			TimeEnum = timeEnum;
			ValueAccess = valueAccess;
			Type = type;
		}

		public Compilation Compilation { get; set; }
		public StringBuilder StringBuilder { get; set; }
		public (ITypeSymbol, INamedTypeSymbol)[] ClassGenMap { get; set; }
		public int Index { get; set; }
		public ImmutableArray<AttributeData> Attrs { get; }
		public INamedTypeSymbol? DftCvtrAttrSmp { get; }
		public INamedTypeSymbol? JsonEnumAttrSmp { get; }
		public bool IsNullable { get; }
		public INamedTypeSymbol? JsonCvtr { get; }
		public int? TimeEnum { get; }
		public string ValueAccess { get; }
		public ITypeSymbol Type { get; }
	}
	private void GenerateReadProperty(GeneratePropertyInfo info)
	{
		var jsonCvtr = info.JsonCvtr;
		var classGenMap = info.ClassGenMap;
		var valueAccess = info.ValueAccess;
		var type = info.Type;
		var isNullable = info.IsNullable;
		var timeEnum = info.TimeEnum;
		var sb = info.StringBuilder;
		var compilation = info.Compilation;
		var dftCvtrAttrSmp = info.DftCvtrAttrSmp;
		var jsonEnumAttrSmp = info.JsonEnumAttrSmp;
		var attrs = info.Attrs;
		var index = info.Index;
		// 已注册转换器
		if (jsonCvtr is null && classGenMap.FirstOrDefault(i => i.Item1.Equals(type, SymbolEqualityComparer.Default)) is var (classGen, cvtr) && classGen is not null)
		{
			sb.Append($$"""{{valueAccess}} = TypeConverterRegistry.Read<{{type.ToDisplayString()}}>(ref reader, options);""");
		}
		// 自定义转换器
		else if (jsonCvtr is not null)
		{
			if (SymbolEqualityComparer.Default.Equals(jsonCvtr.BaseType.OriginalDefinition, compilation.GetTypeByMetadataName(MetadataJsonConverterTypeName)))
				sb.Append($$"""{{valueAccess}} = new {{jsonCvtr.ToDisplayString()}}().Read(ref reader, typeof({{type.ToDisplayString()}}), options);""");
			else
				sb.Append($$"""{{valueAccess}} = new {{jsonCvtr.ToDisplayString()}}().Read(ref reader, typeof({{type.ToDisplayString()}}), options.JsonSerializerOptions);""");
		}
		// 时间
		else if (timeEnum is int timeType)
		{
			switch (timeType)
			{
				case 0:
					sb.Append($"{valueAccess} = TimeSpan.FromMilliseconds(reader.GetDouble());");
					break;
				case 1:
					sb.Append($"{valueAccess} = TimeSpan.FromSeconds(reader.GetDouble());");
					break;
				default:
					sb.Append($$"""{ throw new NotImplementedException(); /* Unsupported time converter type: {{timeType}} */ }""");
					break;
			}
		}
		// 枚举
		else if (type.TypeKind == TypeKind.Enum)
		{
			if (
				!attrs.Any(i => SymbolEqualityComparer.Default.Equals(i.AttributeClass, dftCvtrAttrSmp)) &&
				type.GetAttributes().Any(i => SymbolEqualityComparer.Default.Equals(i.AttributeClass, jsonEnumAttrSmp)))
				sb.Append($$"""{ if (global::RhythmBase.Global.Serialization.EnumConverter.TryParse(ref reader, out {{type.ToDisplayString()}} enumValue{{index}})) {{valueAccess}} = enumValue{{index}}; else return false; }""");
			else
				// - 非枚举或无需序列化器
				sb.Append($$"""{{valueAccess}} = ({{type.ToDisplayString()}})reader.GetInt64();""");
		}
		// 默认类型
		else if (type.SpecialType is not SpecialType.None)
			sb.Append($$"""{{valueAccess}} = reader.Get{{GetJsonReadMethod(type)}}(){{((GetJsonReadMethod(type) == "String" && !isNullable) ? " ?? \"\"" : "")}};""");
		// 其他
		else if (IsConcreteEnumerable(type) is ITypeSymbol elementType)
		{
			string listType = $"System.Collections.Generic.List<{elementType.ToDisplayString()}>";
			sb.AppendLine($$"""
						{
							var list = new {{listType}}();
							if (reader.TokenType == JsonTokenType.StartArray)
							{
								while (reader.Read() && reader.TokenType != JsonTokenType.EndArray)
								{
				""");
			if (elementType.SpecialType is not SpecialType.None)
				sb.Append($$"""  var elementValue = reader.Get{{GetJsonReadMethod(elementType)}}(){{((GetJsonReadMethod(elementType) == "String" && !isNullable) ? " ?? \"\"" : "")}};""");
			else if (elementType.TypeKind == TypeKind.Enum)
				if (
					elementType.GetAttributes().Any(i => SymbolEqualityComparer.Default.Equals(i.AttributeClass, jsonEnumAttrSmp)))
					sb.Append($$"""  global::RhythmBase.Global.Serialization.EnumConverter.TryParse(reader.GetString(), out {{elementType.ToDisplayString()}} elementValue);""");
				else
					// - 非枚举或无需序列化器
					sb.AppendLine($$"""					var elementValue = ({{elementType.ToDisplayString()}})reader.GetInt64();""");
			else
				sb.Append($$"""					var elementValue = TypeConverterRegistry.Read<{{elementType.ToDisplayString()}}>(ref reader, options);""");
			sb.AppendLine($$"""
									list.Add(elementValue);
								}
							}
							{{valueAccess}} = [..list];
						}
				""");
		}
		else
			sb.Append($$"""{{valueAccess}} = TypeConverterRegistry.Read<{{type.ToDisplayString()}}>(ref reader, options);""");
	}
	private class GenerateWritePropertyInfo
	{
		public Compilation Compilation { get; set; }
		public StringBuilder StringBuilder { get; set; }
		public (ITypeSymbol, INamedTypeSymbol)[] ClassGenMap { get; set; }
		public int Index { get; set; }
		public ImmutableArray<AttributeData> Attrs { get; }
		public INamedTypeSymbol? DftCvtrAttrSmp { get; }
		public INamedTypeSymbol? JsonEnumAttrSmp { get; }
		public bool IsNullable { get; }
		public INamedTypeSymbol? JsonCvtr { get; }
		public int? TimeEnum { get; }
		public string ValueAccess { get; }
		public ITypeSymbol Type { get; }
		public string Alias { get; }
		public bool HasCondition { get; }

		public GenerateWritePropertyInfo(Compilation compilation, StringBuilder sb, (ITypeSymbol, INamedTypeSymbol)[] classGenMap, int index, ImmutableArray<AttributeData> attrs, INamedTypeSymbol? dftCvtrAttrSmp, INamedTypeSymbol? jsonEnumAttrSmp, bool isNullable, INamedTypeSymbol? jsonCvtr, int? timeEnum, string valueAccess, ITypeSymbol type, string alias, bool hasCondition)
		{
			Compilation = compilation;
			StringBuilder = sb;
			ClassGenMap = classGenMap;
			Index = index;
			Attrs = attrs;
			DftCvtrAttrSmp = dftCvtrAttrSmp;
			JsonEnumAttrSmp = jsonEnumAttrSmp;
			IsNullable = isNullable;
			JsonCvtr = jsonCvtr;
			TimeEnum = timeEnum;
			ValueAccess = valueAccess;
			Type = type;
			Alias = alias;
			HasCondition = hasCondition;
		}
	}
	private void GenerateWriteProperty(GenerateWritePropertyInfo info)
	{
		var jsonCvtr = info.JsonCvtr;
		var classGenMap = info.ClassGenMap;
		var valueAccess = info.ValueAccess;
		var type = info.Type;
		var isNullable = info.IsNullable;
		var timeEnum = info.TimeEnum;
		var sb = info.StringBuilder;
		var compilation = info.Compilation;
		var dftCvtrAttrSmp = info.DftCvtrAttrSmp;
		var jsonEnumAttrSmp = info.JsonEnumAttrSmp;
		var attrs = info.Attrs;
		var alias = info.Alias;
		var hasCondition = info.HasCondition;
		var metadataJsonConverterType = compilation.GetTypeByMetadataName(MetadataJsonConverterTypeName);
		// 已注册转换器
		if (jsonCvtr is null && classGenMap.FirstOrDefault(i => i.Item1.Equals(type, SymbolEqualityComparer.Default)) is var (classGen, cvtr) && classGen is not null)
		{
			sb.Append($$"""{{(hasCondition ? "{" : "")}} writer.WritePropertyName("{{alias}}"u8); TypeConverterRegistry.Write(writer, {{valueAccess}}, options); {{(hasCondition ? "}" : "")}}""");
		}
		// 自定义转换器
		else if (jsonCvtr is not null)
		{
			if (SymbolEqualityComparer.Default.Equals(jsonCvtr.BaseType.OriginalDefinition, metadataJsonConverterType))
				sb.Append($$"""{ writer.WritePropertyName("{{alias}}"u8); new {{jsonCvtr.ToDisplayString()}}().Write(writer, {{valueAccess}}, options); }""");
			else
				sb.Append($$"""{ writer.WritePropertyName("{{alias}}"u8); new {{jsonCvtr.ToDisplayString()}}().Write(writer, {{valueAccess}}, options.JsonSerializerOptions); }""");
		}
		// 时间
		else if (timeEnum is int timeType)
		{
			switch (timeType)
			{
				case 0:
					sb.Append($"writer.WriteNumber(\"{alias}\"u8, {valueAccess}.TotalMilliseconds);");
					break;
				case 1:
					sb.Append($"writer.WriteNumber(\"{alias}\"u8, {valueAccess}.TotalSeconds);");
					break;
				default:
					sb.Append($$"""{ throw new NotImplementedException(); /* Unsupported time converter type: {{timeType}} */ }""");
					break;
			}
		}
		// 枚举
		else if (type.TypeKind == TypeKind.Enum)
		{
			if (
				!attrs.Any(i => SymbolEqualityComparer.Default.Equals(i.AttributeClass, dftCvtrAttrSmp)) &&
				type.GetAttributes().Any(i => SymbolEqualityComparer.Default.Equals(i.AttributeClass, jsonEnumAttrSmp)))
				sb.Append($"writer.WriteString(\"{alias}\"u8, {valueAccess}.ToEnumUtf8String());");
			else
				sb.Append($"writer.WriteNumber(\"{alias}\"u8, System.Convert.ToInt64({valueAccess}));");
		}
		// 默认类型
		else if (type.SpecialType is not SpecialType.None)
			sb.Append($$"""{ writer.Write{{GetJsonWriterMethod(type)}}("{{alias}}"u8, {{valueAccess}}); }""");
		// 其他
		else if (IsConcreteEnumerable(type) is ITypeSymbol elementType)
		{
			string itemVar = $"item{info.Index}";
			sb.AppendLine($$"""
			{ writer.WritePropertyName("{{alias}}"u8);
				writer.WriteStartArray();
				foreach (var {{itemVar}} in {{valueAccess}})
				{
			""");
			if (elementType.SpecialType is not SpecialType.None)
				sb.Append($$"""  writer.Write{{GetJsonWriterMethod(elementType)}}Value({{itemVar}});""");
			else if (elementType.TypeKind == TypeKind.Enum)
				if (
					elementType.GetAttributes().Any(i => SymbolEqualityComparer.Default.Equals(i.AttributeClass, jsonEnumAttrSmp)))
					sb.Append($$"""  writer.WriteStringValue({{itemVar}}.ToEnumUtf8String());""");
				else
					sb.Append($"writer.WriteNumberValue(System.Convert.ToInt64({valueAccess}));");
			else
				sb.Append($$"""  TypeConverterRegistry.Write(writer, {{itemVar}}, options);""");
			sb.AppendLine($$"""
				}
				writer.WriteEndArray(); }
			""");
		}
		else
			sb.Append($$"""{ writer.WritePropertyName("{{alias}}"u8); TypeConverterRegistry.Write(writer, {{valueAccess}}, options); }""");
	}

	private void GenerateWriteBody(Compilation compilation, StringBuilder sb, ClassGenCvtrInfo info, (ITypeSymbol, INamedTypeSymbol)[] classGenMap)
	{
		//sb.AppendLine("/*\n");

		sb.AppendLine("base.Write(writer, ref value, options);");

		int index = 0;
		var metadataJsonConverterType = compilation.GetTypeByMetadataName(MetadataJsonConverterTypeName);
		foreach (var prop in info.Properties.OrderBy(i => i.Property.Name))
		{
			var attrs = prop.Property.GetAttributes();
			var aliasAttrSmp = compilation.GetTypeByMetadataName(JsonAliasAttrName);
			var condAttrSmp = compilation.GetTypeByMetadataName(JsonConditionAttrName);
			var ignoreAttrSmp = compilation.GetTypeByMetadataName(JsonIgnoreAttrName);
			var jsonCvtrAttrSmp = compilation.GetTypeByMetadataName(JsonConverterAttrName);
			var timeCvtrAttrSmp = compilation.GetTypeByMetadataName(JsonTimeAttrName);
			var dftCvtrAttrSmp = compilation.GetTypeByMetadataName(JsonDefaultSerializerAttrName);
			var jsonEnumAttrSmp = compilation.GetTypeByMetadataName(JsonEnumAttrName);

			bool shouldGenerate = prop.Property.GetMethod is not null &&
				prop.Property.ExplicitInterfaceImplementations.Length == 0 &&
				(
				(
				prop.Property.DeclaredAccessibility.HasFlag(Accessibility.Public) ||
				attrs.FirstOrDefault(i => SymbolEqualityComparer.Default.Equals(i.AttributeClass, aliasAttrSmp)) is not null
				) &&
				attrs.FirstOrDefault(i => SymbolEqualityComparer.Default.Equals(i.AttributeClass, ignoreAttrSmp)) is null
				);
			bool isNullable = prop.Property.Type.NullableAnnotation == NullableAnnotation.Annotated;
			if (shouldGenerate)
			{

				string alias = attrs.FirstOrDefault(i => SymbolEqualityComparer.Default.Equals(i.AttributeClass, aliasAttrSmp) && i.ConstructorArguments.Length == 1)?.ConstructorArguments[0].Value as string
						?? ToLowerCamelCase(prop.Property.ToDisplayParts().Last().ToString());
				string? condition = attrs.FirstOrDefault(i => SymbolEqualityComparer.Default.Equals(i.AttributeClass, condAttrSmp) && i.ConstructorArguments.Length == 1)?.ConstructorArguments[0].Value as string;
				INamedTypeSymbol? jsonCvtr = attrs.FirstOrDefault(i => SymbolEqualityComparer.Default.Equals(i.AttributeClass, jsonCvtrAttrSmp) && i.ConstructorArguments.Length == 1)?.ConstructorArguments[0].Value as INamedTypeSymbol;
				int? timeEnum = attrs.FirstOrDefault(i => SymbolEqualityComparer.Default.Equals(i.AttributeClass, timeCvtrAttrSmp) && i.ConstructorArguments.Length == 1)?.ConstructorArguments[0].Value as int?;

				var type = UnwarpNullable(prop.Property.Type);

				string valueAccess = $"value.{prop.Property.ToDisplayParts().Last().ToString()}";
				if (isNullable)
				{
					valueAccess = $"localValue{index}";
					sb.Append($$"""
						if (value.{{prop.Property.ToDisplayParts().Last().ToString()}} is {{type.ToDisplayString()}} localValue{{index}})
						{ 
				""");
					;
					index++;
				}

				bool hasCondition = false;
				if (!string.IsNullOrEmpty(condition))
				{
					var conditionLines = ReplaceVariableWithName(condition).Split(['\n', '\r'], StringSplitOptions.RemoveEmptyEntries);
					sb.AppendLine($"		if ({string.Join("\n\t\t\t", conditionLines)})");
					hasCondition = true;
				}

				// 已注册转换器
				if (jsonCvtr is null && classGenMap.FirstOrDefault(i => i.Item1.Equals(type, SymbolEqualityComparer.Default)) is var (classGen, cvtr) && classGen is not null)
				{
					sb.Append($$"""{{(hasCondition ? "{" : "")}} writer.WritePropertyName("{{alias}}"u8); TypeConverterRegistry.Write(writer, {{valueAccess}}, options); {{(hasCondition ? "}" : "")}}""");
				}
				// 自定义转换器
				else if (jsonCvtr is not null)
				{
					if (SymbolEqualityComparer.Default.Equals(jsonCvtr.BaseType.OriginalDefinition, metadataJsonConverterType))
						sb.Append($$"""{ writer.WritePropertyName("{{alias}}"u8); new {{jsonCvtr.ToDisplayString()}}().Write(writer, {{valueAccess}}, options); }""");
					else
						sb.Append($$"""{ writer.WritePropertyName("{{alias}}"u8); new {{jsonCvtr.ToDisplayString()}}().Write(writer, {{valueAccess}}, options.JsonSerializerOptions); }""");
				}
				// 时间
				else if (timeEnum is int timeType)
				{
					switch (timeType)
					{
						case 0:
							sb.Append($"writer.WriteNumber(\"{alias}\"u8, {valueAccess}.TotalMilliseconds);");
							break;
						case 1:
							sb.Append($"writer.WriteNumber(\"{alias}\"u8, {valueAccess}.TotalSeconds);");
							break;
						default:
							sb.Append($$"""{ throw new NotImplementedException(); /* Unsupported time converter type: {{timeType}} */ }""");
							break;
					}
				}
				// 枚举
				else if (type.TypeKind == TypeKind.Enum)
				{
					if (
						!attrs.Any(i => SymbolEqualityComparer.Default.Equals(i.AttributeClass, dftCvtrAttrSmp)) &&
						type.GetAttributes().Any(i => SymbolEqualityComparer.Default.Equals(i.AttributeClass, jsonEnumAttrSmp)))
						sb.Append($"writer.WriteString(\"{alias}\"u8, {valueAccess}.ToEnumUtf8String());");
					else
						// - 非枚举或无需序列化器
						sb.Append($"writer.WriteNumber(\"{alias}\"u8, System.Convert.ToInt64({valueAccess}));");
				}
				// 默认类型
				else if (type.SpecialType is not SpecialType.None)
					sb.Append($$"""{ writer.Write{{GetJsonWriterMethod(type)}}("{{alias}}"u8, {{valueAccess}}); }""");
				// 其他
				else if (IsConcreteEnumerable(type) is ITypeSymbol elementType)
				{
					string itemVar = $"item{index}";
					sb.AppendLine($$"""
				{ writer.WritePropertyName("{{alias}}"u8);
					writer.WriteStartArray();
					foreach (var {{itemVar}} in {{valueAccess}})
					{
				""");
					// 根据 elementType 写入每个元素
					if (elementType.SpecialType is not SpecialType.None)
						sb.Append($$"""  writer.Write{{GetJsonWriterMethod(elementType)}}Value({{itemVar}});""");
					else if (elementType.TypeKind == TypeKind.Enum)
						if (
							elementType.GetAttributes().Any(i => SymbolEqualityComparer.Default.Equals(i.AttributeClass, jsonEnumAttrSmp)))
							sb.Append($$"""  writer.WriteStringValue({{itemVar}}.ToEnumUtf8String());""");
						else
							// - 非枚举或无需序列化器
							sb.Append($"writer.WriteNumberValue(System.Convert.ToInt64({valueAccess}));");
					else
						sb.Append($$"""  TypeConverterRegistry.Write(writer, {{itemVar}}, options);""");
					sb.AppendLine($$"""
					}
					writer.WriteEndArray(); }
				""");
				}
				else
					sb.Append($$"""{ writer.WritePropertyName("{{alias}}"u8); TypeConverterRegistry.Write(writer, {{valueAccess}}, options); }""");
				if (isNullable)
					sb.AppendLine(" }");
				else
					sb.AppendLine();
			}

			// JsonFlatten: 展平子属性写入
			var jsonFlattenAttrSmp = compilation.GetTypeByMetadataName(JsonFlattenAttrName);
			AttributeData[] jsonFlattenAttrs = attrs.Where(i => SymbolEqualityComparer.Default.Equals(i.AttributeClass, jsonFlattenAttrSmp)).ToArray();
			if (jsonFlattenAttrs.Length > 0)
			{
				string? parentCondition = attrs.FirstOrDefault(i => SymbolEqualityComparer.Default.Equals(i.AttributeClass, condAttrSmp) && i.ConstructorArguments.Length == 1)?.ConstructorArguments[0].Value as string;
				var parentType = UnwarpNullable(prop.Property.Type);
				bool parentIsNullableValueType = isNullable && parentType.TypeKind == TypeKind.Struct;
				foreach (var attr in jsonFlattenAttrs)
				{
					string subPropName = attr.ConstructorArguments[0].Value is string s ? s : throw new InvalidOperationException("Invalid JsonFlatten attribute: missing property name.");
					string aliasName = attr.ConstructorArguments[1].Value is string s2 ? s2 : ToLowerCamelCase(subPropName);
					int mode = attr.ConstructorArguments.Length >= 3 && attr.ConstructorArguments[2].Value is int m ? m : 3;
					if ((mode & 2) == 0) continue; // bit 1 = WriteOnly

					var subProp = parentType.GetMembers().FirstOrDefault(m => m.Name == subPropName) as IPropertySymbol;
					if (subProp is null) continue;

					bool subIsNullable = subProp.Type.NullableAnnotation == NullableAnnotation.Annotated;
					var subType = UnwarpNullable(subProp.Type);
					string parentAccess = $"value.{prop.Property.Name}";
					string flatValueAccess = parentIsNullableValueType
						? $"{parentAccess}.Value.{subPropName}"
						: $"{parentAccess}.{subPropName}";

					// 查找子属性上的 JsonAlias / JsonTime / JsonConverter / JsonDefaultSerializer
					var subAttrs = subProp.GetAttributes();
					INamedTypeSymbol? subJsonCvtr = subAttrs.FirstOrDefault(i => SymbolEqualityComparer.Default.Equals(i.AttributeClass, jsonCvtrAttrSmp) && i.ConstructorArguments.Length == 1)?.ConstructorArguments[0].Value as INamedTypeSymbol;
					int? subTimeEnum = subAttrs.FirstOrDefault(i => SymbolEqualityComparer.Default.Equals(i.AttributeClass, timeCvtrAttrSmp) && i.ConstructorArguments.Length == 1)?.ConstructorArguments[0].Value as int?;
					string? subCondition = subAttrs.FirstOrDefault(i => SymbolEqualityComparer.Default.Equals(i.AttributeClass, condAttrSmp) && i.ConstructorArguments.Length == 1)?.ConstructorArguments[0].Value as string;

					// 父属性 JsonCondition 影响子属性
					if (!string.IsNullOrEmpty(parentCondition))
					{
						var parentConditionLines = ReplaceVariableWithName(parentCondition).Split(['\n', '\r'], StringSplitOptions.RemoveEmptyEntries);
						sb.AppendLine($"if ({string.Join("\n\t\t\t", parentConditionLines)})");
					}

					// 父对象为空时跳过
					if (isNullable)
						sb.Append($$"""if ({{parentAccess}} is not null) """);

					bool hasSubCondition = false;
					if (!string.IsNullOrEmpty(subCondition))
					{
						var conditionLines = ReplaceVariableWithName(subCondition).Split(['\n', '\r'], StringSplitOptions.RemoveEmptyEntries);
						sb.AppendLine($"if ({string.Join("\n\t\t\t", conditionLines)})");
						hasSubCondition = true;
					}

					// 可空子属性：模式匹配获取非空值
					if (subIsNullable)
					{
						string localVar = $"__flatValue{index}";
						sb.Append($$"""if ({{flatValueAccess}} is {{subType.ToDisplayString()}} {{localVar}}) """);
						flatValueAccess = localVar;
						index++;
					}

					// 生成子属性写入
					GenerateWriteProperty(new GenerateWritePropertyInfo(compilation, sb, classGenMap, index, subAttrs, dftCvtrAttrSmp, jsonEnumAttrSmp, subIsNullable, subJsonCvtr, subTimeEnum, flatValueAccess, subType, aliasName, hasSubCondition));
				}
			}
		}
		//sb.AppendLine("*/throw new NotImplementedException();");
	}
	private string GetJsonReadMethod(ITypeSymbol type)
	{
		return type.SpecialType switch
		{
			SpecialType.System_Boolean => "Boolean",
			SpecialType.System_Byte => "Byte",
			SpecialType.System_Char => "String",
			SpecialType.System_Decimal => "Decimal",
			SpecialType.System_Double => "Double",
			SpecialType.System_Single => "Single",
			SpecialType.System_Int16 => "Int16",
			SpecialType.System_Int32 => "Int32",
			SpecialType.System_Int64 => "Int64",
			SpecialType.System_SByte => "SByte",
			SpecialType.System_UInt16 => "UInt16",
			SpecialType.System_UInt32 => "UInt32",
			SpecialType.System_UInt64 => "UInt64",
			SpecialType.System_String => "String",
			_ => throw new NotSupportedException($"Unsupported property type: {type.ToDisplayString()}")
		};
	}
	private string GetJsonWriterMethod(ITypeSymbol type)
	{
		return type.SpecialType switch
		{
			SpecialType.System_Boolean => "Boolean",
			SpecialType.System_Byte => "Number",
			SpecialType.System_Char => "String",
			SpecialType.System_Decimal or
			SpecialType.System_Double or
			SpecialType.System_Single or
			SpecialType.System_Byte or
			SpecialType.System_Int16 or
			SpecialType.System_Int32 or
			SpecialType.System_Int64 or
			SpecialType.System_SByte or
			SpecialType.System_UInt16 or
			SpecialType.System_UInt32 or
			SpecialType.System_UInt64 => "Number",
			SpecialType.System_String => "String",
			_ => throw new NotSupportedException($"Unsupported property type: {type.ToDisplayString()}")
		};
	}

	private void GenerateConverter(IncrementalGeneratorInitializationContext context, IncrementalValueProvider<(((string?, List<Diagnostic>), Compilation), ((IClassGen[], ClassGenAttr)[], (ITypeSymbol, INamedTypeSymbol)[]))> jsonClassCvtrMapGenInfo)
	{
		context.RegisterSourceOutput(jsonClassCvtrMapGenInfo, (ctx, classGenInfoArray) =>
		{
			var (idAndCompilation, classGensAndClassGenMap) = classGenInfoArray;
			var ((registryId, diagnostics), compilation) = idAndCompilation;
			var (classGens, classGenMap) = classGensAndClassGenMap;
			foreach (var diag in diagnostics)
				ctx.ReportDiagnostic(diag);
			if (string.IsNullOrEmpty(registryId) || registryId == CoreNs)
				return;
			string ns = $"RhythmBase.{registryId}.Serialization";
			StringBuilder classCvtrSb = new();
			StringBuilder classMapSb = new();
			classCvtrSb.AppendLine($"""
						// <auto-generated/>
						#nullable enable
						
						using System;
						using RhythmBase.Global.Serialization;
						using System.Text.Json;
						using static RhythmBase.Global.Serialization.EnumConverter;
						
						namespace {ns};
						""");

			classMapSb.AppendLine($$"""
						internal static class EventConverterMap {
						""");


			foreach (var classGen in classGens)
			{
				var classes = classGen.Item1;
				var rootConverterTypeBase = classGen.Item2.RootConverterType.OriginalDefinition.BaseType;
				if (rootConverterTypeBase is null || rootConverterTypeBase.IsGenericType)
				{
					ctx.ReportDiagnostic(Diagnostic.Create(GenericConverterBaseMustBeNonGenericRule, classGen.Item2.RootConverterType.Locations.FirstOrDefault(), rootConverterTypeBase?.ToDisplayString(), classGen.Item2.RootConverterType.ToDisplayString()));
					return;
				}
				classMapSb.AppendLine($$"""
							internal static {{rootConverterTypeBase.ToDisplayString()}} GetConverter({{classGen.Item2.EnumType.ToDisplayString()}} type) => type switch
							{
						""");
				foreach (var c in classes.OrderBy(i => i.ICGClassType.Name))
				{
					var t = c.ICGClassType;
					var baseType = t.BaseType;
					IClassGen? baseRecord = classes.FirstOrDefault(d => baseType.Equals(d.ICGClassType, SymbolEqualityComparer.Default));
					bool isDirectImplementation = t.TypeKind == TypeKind.Struct ||
							baseType.Equals(classGen.Item2.RootType, SymbolEqualityComparer.Default);
					if (baseRecord is null && !isDirectImplementation) continue;
					if (c is ClassGenCvtrInfo c1)
					{
						string baseConverterName;
						if (c1.ClassType.IsAbstract)
						{
							ctx.ReportDiagnostic(Diagnostic.Create(GenericConverterBaseMustBeNonGenericRule, c1.ClassType.Locations.FirstOrDefault(), c1.ClassType.ToDisplayString(), "abstract classes cannot be converted"));
							continue;
						}
						ISymbol enumValueSymbol = c1.ClassTypeEnum;
						INamedTypeSymbol ocvtr = classGen.Item2.RootConverterType.OriginalDefinition.Construct(t);
						if (baseRecord is ClassGenCvtrInfo baseRecord1)
						{
							baseConverterName = $"{ns}.{baseRecord1.ClassType.Name}Converter";
						}
						else if (baseRecord is ClassRefConverterInfo baseRecord2)
						{
							var baseConverter = baseRecord2.ConverterType;
							if (baseConverter.IsGenericType)
								baseConverterName = baseConverter.OriginalDefinition.Construct(t).ToDisplayString();
							else
							{
								ctx.ReportDiagnostic(Diagnostic.Create(NonGenericBaseConverterRule, c1.ClassType.Locations.FirstOrDefault(), baseConverter.ToDisplayString(), $"{ns}.{baseRecord2.ClassType.Name}Converter"));
								continue;
							}
						}
						else
						{
							baseConverterName = ocvtr.ToDisplayString();
						}
						classCvtrSb.AppendLine($$"""
						internal class {{t.Name}}Converter : {{baseConverterName}}
						{
							protected override bool Read(ref Utf8JsonReader reader, ref {{t.ToDisplayString()}} value, global::RhythmBase.Global.Serialization.MetadataJsonSerializerOptions options)
							{
						""");
						if (c1.Properties.Any(i => GetShouldGenerate(i, compilation)))
							GenerateReadBody(compilation, classCvtrSb, c1, classGenMap);
						else
							classCvtrSb.AppendLine($$"""
								return base.Read(ref reader, ref value, options);
						""");
						classCvtrSb.AppendLine($$"""
							}
							protected override void Write(Utf8JsonWriter writer, ref {{t.ToDisplayString()}} value, global::RhythmBase.Global.Serialization.MetadataJsonSerializerOptions options)
							{
						""");
						GenerateWriteBody(compilation, classCvtrSb, c1, classGenMap);
						classCvtrSb.AppendLine("""
							}
						}
						""");
					}
					switch (c)
					{
						case ClassGenCvtrInfo c2:
							classMapSb.AppendLine($$"""
								{{c2.ClassTypeEnum.ToDisplayString()}} => new {{t.Name}}Converter(),
						""");
							break;
						case ClassRefConverterInfo c3:
							if (!c3.ClassType.IsAbstract && c3.ClassTypeEnum is not null)
								classMapSb.AppendLine($$"""
								{{c3.ClassTypeEnum.ToDisplayString()}} => new {{c3.ConverterType.ToDisplayString()}}(),
						""");
							break;
					}
				}
				classMapSb.AppendLine($$"""
								_ => throw new NotImplementedException(),
							};
						""");
			}
			classMapSb.AppendLine("""
						}
						""");
			classCvtrSb.Append(classMapSb);

			ctx.AddSource($"Converters.{registryId}.g.cs", classCvtrSb.ToString());
		});
	}
	private class EventTypeRegistryGenerationInfo
	{
		public INamedTypeSymbol RootClassType { get; set; }
		public INamedTypeSymbol ClassTypeEnum { get; set; }
		public IEnumerable<INamedTypeSymbol> Classes { get; set; }
		public Dictionary<INamedTypeSymbol, HashSet<ISymbol>> EventTypeRegistry { get; set; }
		public Dictionary<INamedTypeSymbol, ISymbol> ClassEnumDoubleMap { get; internal set; }
		public INamedTypeSymbol? FallbackClassType { get; internal set; }
		public ISymbol? FallbackClassTypeEnum { get; internal set; }
		public List<Diagnostic> Diagnostics { get; set; } = new();
	}
	private static void GenerateEventTypeUtils(SourceProductionContext spc, (((string?, List<Diagnostic>), Compilation), EventTypeRegistryGenerationInfo[]) classSymbols)
	{
		((var registryId, var pipelineDiagnostics), var compilation, var infos) = (classSymbols.Item1.Item1, classSymbols.Item1.Item2, classSymbols.Item2);
		foreach (var diag in pipelineDiagnostics)
			spc.ReportDiagnostic(diag);
		foreach (var info in infos)
			foreach (var diag in info.Diagnostics)
				spc.ReportDiagnostic(diag);
		if (string.IsNullOrEmpty(registryId) || registryId == CoreNs || infos.Length == 0)
			return;
		var jsonEnumAttrSmp = compilation.GetTypeByMetadataName(JsonEnumAttrName);
		StringBuilder sb = new();
		sb.AppendLine($$"""
// <auto-generated/>
#nullable enable
using System;
			namespace RhythmBase.{{registryId}}.Serialization;

/// <summary>
/// Utility class for converting between event types and enumerations.
/// </summary>
public static partial class EventTypeRegistry
{
""");
		for (int i = 0; i < infos.Length; i++)
		{
			string indexPostfix = infos.Length > 1 ? $"{i}" : "";
			string enumPostfix = infos.Length > 1 ? $"{infos[i].ClassTypeEnum.Name}" : "";
			string classPostfix = infos.Length > 1 ? $"{infos[i].RootClassType.Name}" : "";
			EventTypeRegistryGenerationInfo? info = infos[i];
			int maxTypeStrLength = 100;
			int maxEnumStrLength = 100;
			maxTypeStrLength = info.EventTypeRegistry.Keys
					.Max(i => i.ToDisplayString().Length)
					 + 13;
			maxEnumStrLength = info.ClassEnumDoubleMap.Values
					.Max(i => i.ToDisplayString().Length);

			sb.AppendLine($$"""
	private static System.Collections.ObjectModel.ReadOnlyCollection<Type>? _t{{indexPostfix}};
	private static System.Collections.ObjectModel.ReadOnlyDictionary<System.Type, RhythmBase.Global.Components.ReadOnlyEnumCollection<{{info.ClassTypeEnum.ToDisplayString()}}>>? _t2e{{indexPostfix}};
	private static System.Collections.ObjectModel.ReadOnlyDictionary<{{info.ClassTypeEnum.ToDisplayString()}}, System.Type>? _e2t{{indexPostfix}};
	private static System.Collections.ObjectModel.ReadOnlyCollection<Type> _types{{indexPostfix}} => _t{{indexPostfix}} ??= new(new Type[]
	{
""");
			foreach (var classSymbol in info.Classes)
			{
				sb.AppendLine($"\t\ttypeof({classSymbol.ToDisplayString()}),");
			}
			sb.AppendLine($$"""
	});
	private static System.Collections.ObjectModel.ReadOnlyDictionary<System.Type, RhythmBase.Global.Components.ReadOnlyEnumCollection<{{info.ClassTypeEnum.ToDisplayString()}}>> _type2enums{{indexPostfix}} => _t2e{{indexPostfix}} ??= new(new Dictionary<System.Type, RhythmBase.Global.Components.ReadOnlyEnumCollection<{{info.ClassTypeEnum.ToDisplayString()}}>>()
	{
""");
			string indent = new(' ', maxTypeStrLength);
			foreach (var pair in info.EventTypeRegistry)
			{
				if (pair.Value.Count == 0)
					continue;
				sb.AppendLine($$"""
		[typeof({{pair.Key.ToDisplayString()}})] ={{new string(' ', maxTypeStrLength - pair.Key.ToDisplayString().Length - 13)}} new RhythmBase.Global.Components.ReadOnlyEnumCollection<{{info.ClassTypeEnum.ToDisplayString()}}>(
		{{indent}}{{string.Join($",\n\t\t{indent}", pair.Value.OrderBy(i => i.Name).Select(i => $"{i.ToDisplayString()}"))}}),
""");
			}
			sb.AppendLine($$"""
	});
	private static System.Collections.ObjectModel.ReadOnlyDictionary<{{info.ClassTypeEnum.ToDisplayString()}}, System.Type> _enum2type{{indexPostfix}} => _e2t{{indexPostfix}} ??= new(new Dictionary<{{info.ClassTypeEnum.ToDisplayString()}}, System.Type>()
	{
""");
			foreach (var pair in info.ClassEnumDoubleMap)
				sb.AppendLine($"\t\t[{pair.Value.ToDisplayString()}] ={new string(' ', maxEnumStrLength - pair.Value.ToDisplayString().Length)} typeof({pair.Key.ToDisplayString()}),");
			sb.AppendLine($$"""
	});
	/// <summary>
	/// Converts a type to its corresponding <see cref="{{info.ClassTypeEnum.ToDisplayString()}}" /> enumeration.
	/// </summary>
	/// <param name="type">The type to convert.</param>
	/// <returns>The corresponding <see cref="{{info.ClassTypeEnum.ToDisplayString()}}" /> enumeration.</returns>
	/// <exception cref="IllegalEventTypeException">Thrown when no matching <see cref="{{info.ClassTypeEnum.ToDisplayString()}}" /> is found or multiple matching <see cref="{{info.ClassTypeEnum.ToDisplayString()}}" /> are found.</exception>  
	public static {{info.ClassTypeEnum.ToDisplayString()}} ToEnum{{enumPostfix}}(Type type)
	{
		{{info.ClassTypeEnum.ToDisplayString()}} v;
		if (_type2enums{{indexPostfix}} == null)
		{
			string name = type.Name;
			if (!Enum.TryParse(name, out {{info.ClassTypeEnum.ToDisplayString()}} result))
			{
				throw new IllegalEventTypeException(type, "Unable to find a matching EventType.");
			}
			v = result;
		}
		else
		{
			try
			{
				v = _type2enums{{indexPostfix}}[type].Single();
			}
			catch (Exception)
			{
				throw new IllegalEventTypeException(type, "Multiple matching EventTypes were found. Please check if the type is an abstract class type.", new ArgumentException("Multiple matching EventTypes were found. Please check if the type is an abstract class type.", nameof(type)));
			}
		}
		return v;
	}
	/// <summary>
	/// Converts a generic event type to its corresponding <see cref="{{info.ClassTypeEnum.ToDisplayString()}}" /> enumeration.
	/// </summary>
	/// <typeparam name="TEvent">The generic event type to convert.</typeparam>
	/// <returns>The corresponding <see cref="{{info.ClassTypeEnum.ToDisplayString()}}" /> enumeration.</returns>
	public static {{info.ClassTypeEnum.ToDisplayString()}} ToEnum{{enumPostfix}}<TEvent>() where TEvent : {{info.RootClassType.ToDisplayString()}}, new() => ToEnum{{enumPostfix}}(typeof(TEvent));
	/// <summary>
	/// Converts a type to a collection of corresponding <see cref="{{info.ClassTypeEnum.ToDisplayString()}}" /> enumerations.
	/// </summary>
	/// <param name="type">The type to convert.</param>
	/// <returns>A collection of corresponding <see cref="{{info.ClassTypeEnum.ToDisplayString()}}" /> enumerations.</returns>
	/// <exception cref="IllegalEventTypeException">Thrown when the type does not exist in the <see cref="{{info.ClassTypeEnum.ToDisplayString()}}" /> registry.</exception>
	public static ReadOnlyEnumCollection<{{info.ClassTypeEnum.ToDisplayString()}}> ToEnums{{enumPostfix}}(Type type)
	{
		return _type2enums{{indexPostfix}}.TryGetValue(type, out var value) ? value : throw new IllegalEventTypeException(type);
	}
	/// <summary>
	/// Converts a generic event type to a collection of corresponding <see cref="{{info.ClassTypeEnum.ToDisplayString()}}" /> enumerations.
	/// </summary>
	/// <typeparam name="TEvent">The generic event type to convert.</typeparam>
	/// <returns>A collection of corresponding <see cref="{{info.ClassTypeEnum.ToDisplayString()}}" /> enumerations.</returns>
	public static ReadOnlyEnumCollection<{{info.ClassTypeEnum.ToDisplayString()}}> ToEnums{{enumPostfix}}<TEvent>() where TEvent : {{info.RootClassType.ToDisplayString()}} => ToEnums{{enumPostfix}}(typeof(TEvent));
	/// <summary>
	/// Converts an <see cref="{{info.ClassTypeEnum.ToDisplayString()}}" /> enumeration to its corresponding Type.
	/// </summary>
	/// <param name="type">The <see cref="{{info.ClassTypeEnum.ToDisplayString()}}" /> enumeration to convert.</param>
	/// <returns>The corresponding Type.</returns>  
	/// <exception cref="IllegalEventTypeException">Thrown when the value does not exist in the <see cref="{{info.ClassTypeEnum.ToDisplayString()}}" /> enumeration.</exception>
	public static Type ToType(this {{info.ClassTypeEnum.ToDisplayString()}} type)
	{
		if (_enum2type{{indexPostfix}} == null)
			return Type.GetType($"{{info.RootClassType.ContainingNamespace.ToDisplayString()}}.{type}") ?? throw new InvalidOperationException(
					$"Illegal Type: {type}.");
		if (_enum2type{{indexPostfix}}.TryGetValue(type, out Type t))
			return t;
		throw new IllegalEventTypeException(type.ToString(), "This value does not exist in the {{info.ClassTypeEnum.ToDisplayString()}} enumeration.");
	}
""");
		}
		if (infos.Length > 0 && !infos.Any(i => i.ClassTypeEnum.GetAttributes().Any(a => a.AttributeClass?.Equals(jsonEnumAttrSmp, SymbolEqualityComparer.Default) ?? false)))
		{
			sb.AppendLine($$"""
	/// <summary>
	/// Converts a string representation of an event type to its corresponding Type.
	/// </summary>
	/// <param name="type">The string representation of the event type.</param>
	/// <returns>The corresponding Type.</returns>
	public static Type ToType(string type)
	{
""");
			for (int i = 0; i < infos.Length; i++)
			{
				var info = infos[i];
				if (info.ClassTypeEnum.GetAttributes().Any(a => a.AttributeClass?.Equals(jsonEnumAttrSmp, SymbolEqualityComparer.Default) ?? false))
					sb.AppendLine($$"""
		if (global::RhythmBase.Global.Serialization.EnumConverter.TryParse(type, out {{info.ClassTypeEnum.ToDisplayString()}} result{{i}}))
			return result{{i}}.ToType();
""");
			}
			sb.AppendLine($$"""
		return typeof({{(infos.Length == 1 ? (infos[0].FallbackClassType?.ToDisplayString() ?? infos[0].RootClassType.ToDisplayString()) : "object")}});
	}
""");
		}
		sb.AppendLine("""
}
""");

		// Generate UnhandledFieldHelper with RegisterForXXX methods
		bool hasAnyInterface = infos.Any(info => info.EventTypeRegistry.Keys.Any(t => t.TypeKind == TypeKind.Interface && info.EventTypeRegistry[t].Count > 0));
		if (hasAnyInterface)
		{
			var generatedMethods = new HashSet<string>();
			sb.AppendLine($$"""
/// <summary>
/// Helper methods for registering unhandled field handlers with interface-based matching.
/// </summary>
internal static class UnhandledFieldHelper
{
	[System.Runtime.CompilerServices.ModuleInitializer]
	internal static void Initialize()
	{
		RhythmBase.Global.Serialization.UnhandledFieldRegistry.Configure(type =>
		{
""");
			for (int i = 0; i < infos.Length; i++)
			{
				string enumPostfix = infos.Length > 1 ? $"{infos[i].ClassTypeEnum.Name}" : "";
				string enumType = infos[i].ClassTypeEnum.ToDisplayString();
				sb.AppendLine($$"""
			try
			{
				var enums = EventTypeRegistry.ToEnums{{enumPostfix}}(type);
				return (int v) => enums.Contains(({{enumType}})v);
			}
			catch { }
""");
			}
			sb.AppendLine($$"""
			return (int _) => false;
		});
	}
""");
			for (int i = 0; i < infos.Length; i++)
			{
				EventTypeRegistryGenerationInfo? info = infos[i];
				string enumPostfix = infos.Length > 1 ? $"_{info.ClassTypeEnum.Name}" : "";

				foreach (var pair in info.EventTypeRegistry)
				{
					if (pair.Key.TypeKind != TypeKind.Interface)
						continue;

					var interfaceType = pair.Key;
					string interfaceName = interfaceType.ToDisplayString();
					string methodName = $"RegisterFor{interfaceType.Name}";

					if (!generatedMethods.Add(methodName))
						continue;

					var concreteTypes = new List<INamedTypeSymbol>();
					foreach (var type in info.EventTypeRegistry.Keys)
					{
						if (type.TypeKind == TypeKind.Interface || type.IsAbstract)
							continue;
						if (type.AllInterfaces.Any(iface => SymbolEqualityComparer.Default.Equals(iface, interfaceType)))
							concreteTypes.Add(type);
					}

					if (concreteTypes.Count == 0)
						continue;

					sb.AppendLine($$"""
	/// <summary>
	/// Registers an unhandled field handler for all concrete types implementing <see cref="{{interfaceName}}"/>.
	/// </summary>
	public static void {{methodName}}(string fieldName, RhythmBase.Global.Serialization.UnhandledPropertyHandler<{{interfaceName}}> handler)
	{
""");

					foreach (var concreteType in concreteTypes.OrderBy(t => t.Name))
					{
						string concreteName = concreteType.ToDisplayString();
						sb.AppendLine($$"""
		RhythmBase.Global.Serialization.UnhandledFieldRegistry.Register<{{concreteName}}>(fieldName,
			(ref {{concreteName}} t, System.Text.Json.JsonElement v) =>
			{ ref {{interfaceName}} e = ref System.Runtime.CompilerServices.Unsafe.As<{{concreteName}}, {{interfaceName}}>(ref t); return handler(ref e, v); });
""");
					}

					sb.AppendLine("""
	}
""");
				}
			}
			sb.AppendLine("""
}
""");
		}

		string filename = $"EventTypeRegistry.{registryId}.g.cs";
		spc.AddSource(filename, sb.ToString());
	}

}