using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Diagnostics;
using System.Text;

namespace RhythmBase.Generator;

public partial class ConverterGenerator
{
	private static void GenerateEventTypeUtils(SourceProductionContext spc, ImmutableArray<ClassInfo?> classSymbols, GenerationConfig config)
	{
		var validClassSymbols = classSymbols
			.Where(i =>
			{
				if (i is not ClassInfo ci) return false;
				if (ci.Type.IsAbstract) return false;
				if (ci.Type.IsGenericType) return false;
				if (!(ci.NeedSerializer || ci.HasSerializer)) return false;
				return true;
			})
			.Cast<ClassInfo>()
			.OrderBy(i => i.Name)
			.ToArray();
		marks.Add($"{validClassSymbols.Length}");
		int maxLength = validClassSymbols
			.Max(i => i.Name.Length);

		IOrderedEnumerable<ClassInfo> validClassSymbolsWithAbstract = classSymbols
			.Where(i =>
			{
				if (i is not ClassInfo ci) return false;
				if (ci.Type.IsGenericType) return false;
				return true;
			})
			.Cast<ClassInfo>()
			.OrderBy(i => i.Name);

		Dictionary<ISymbol, HashSet<ClassInfo>> typeLink = validClassSymbolsWithAbstract
			 .Select(i => i.Type)
			 .ToDictionary(
				 i => i as ISymbol,
				 i =>
				 {
					 HashSet<ClassInfo> result = [..validClassSymbolsWithAbstract.Where(j => InheritsOrImplements(j.Type, i))];
					 return result;
				 },
				 SymbolEqualityComparer.Default);

		foreach (var pair in typeLink)
		{
			List<ClassInfo> abstracts = [];
			int abstractCount;
			do
			{
				abstractCount = abstracts.Count;
				foreach (ClassInfo abs in abstracts)
				{
					if (typeLink.TryGetValue(abs.Type, out var result))
						pair.Value.UnionWith(result);
				}
				abstracts = [.. pair.Value.Where(i => i.Type.IsAbstract)];
			}
			while (abstractCount < abstracts.Count);
			pair.Value.RemoveWhere(abstracts.Contains);
		}

		StringBuilder sb = new();
		sb.AppendLine($$"""
// <auto-generated/>
#nullable enable
using System;
namespace {{config.TargetUtilsNamespace}};
partial class {{config.TargetUtilsClassName}}
{
	private static System.Collections.ObjectModel.ReadOnlyDictionary<{{config.ClassTypeEnumFullname}}, {{config.TargetConverterNamespace}}.{{config.BaseConverterClassName}}Base>? _c;
	private static System.Collections.ObjectModel.ReadOnlyCollection<Type>? _t;
	private static System.Collections.ObjectModel.ReadOnlyDictionary<System.Type, RhythmBase.Global.Components.ReadOnlyEnumCollection<{{config.ClassTypeEnumFullname}}>>? _t2e;
	private static System.Collections.ObjectModel.ReadOnlyDictionary<{{config.ClassTypeEnumFullname}}, System.Type>? _e2t;
	internal static System.Collections.ObjectModel.ReadOnlyDictionary<{{config.ClassTypeEnumFullname}}, {{config.TargetConverterNamespace}}.{{config.BaseConverterClassName}}Base> converters => _c ??= new(new Dictionary<{{config.ClassTypeEnumFullname}}, {{config.TargetConverterNamespace}}.{{config.BaseConverterClassName}}Base>()
	{
""");
		foreach (ClassInfo info in validClassSymbols)
		{
			sb.AppendLine($"\t\t[{config.ClassTypeEnumFullname}.{ToShorter(info.Name)}] ={new string(' ', maxLength - info.Name.Length)} new {config.TargetConverterNamespace}.{config.BaseConverterClassName}{ToShorter(info.Name)}(),");
		}
		sb.AppendLine($$"""
	});
	private static System.Collections.ObjectModel.ReadOnlyCollection<Type> _types => _t ??= new(new Type[]
	{
""");
		foreach (ClassInfo classInfo in validClassSymbolsWithAbstract)
		{
			sb.AppendLine($"\t\ttypeof({classInfo.Name}),");
		}
		sb.AppendLine($$"""
	});
	private static System.Collections.ObjectModel.ReadOnlyDictionary<System.Type, RhythmBase.Global.Components.ReadOnlyEnumCollection<{{config.ClassTypeEnumFullname}}>> _type2enums => _t2e ??= new(new Dictionary<System.Type, RhythmBase.Global.Components.ReadOnlyEnumCollection<{{config.ClassTypeEnumFullname}}>>()
	{
""");
		string indent = new(' ', maxLength + 13);
		foreach (ClassInfo classInfo in validClassSymbolsWithAbstract)
		{
			if (typeLink[classInfo.Type].Count == 0)
				continue;
			sb.AppendLine($$"""
			[typeof({{classInfo.Name}})] ={{new string(' ', maxLength - classInfo.Name.Length)}} new RhythmBase.Global.Components.ReadOnlyEnumCollection<{{config.ClassTypeEnumFullname}}>(2, // {{typeLink[classInfo.Type].Count}}
			{{indent}}{{string.Join($",\n\t\t{indent}", typeLink[classInfo.Type].OrderBy(i => i.Name).Select(i => $"{config.ClassTypeEnumFullname}.{ToShorter(i.Name)}"))}}),
""");
		}
		sb.AppendLine($$"""
	});
	private static System.Collections.ObjectModel.ReadOnlyDictionary<{{config.ClassTypeEnumFullname}}, System.Type> _enum2type => _e2t ??= new(new Dictionary<{{config.ClassTypeEnumFullname}}, System.Type>()
	{
""");
		foreach (ClassInfo info in validClassSymbols)
		{
			sb.AppendLine($"\t\t[{config.ClassTypeEnumFullname}.{ToShorter(info.Name)}] ={new string(' ', maxLength - info.Name.Length)} typeof({info.Name}),");
		}
		sb.AppendLine($$"""
	});
""");
		foreach (var classInfo in validClassSymbolsWithAbstract)
		{
			sb.AppendLine($"// {classInfo.Type.Name}");
		}
		sb.AppendLine("}");

		spc.AddSource($"{config.TargetUtilsClassName}.{config.Id}.g.cs", sb.ToString());
	}
	private record struct ADFilterInfo(INamedTypeSymbol Type, AttributeData? specialNameAttribute);
    private static void GenerateFilterTypeUtilsForEnum(IncrementalGeneratorInitializationContext context)
	{
		List<string> marks = [];
        IncrementalValueProvider<ImmutableArray<ADFilterInfo>> types = context.SyntaxProvider.CreateSyntaxProvider(
			predicate: static (s, ct) => s is StructDeclarationSyntax,
			transform: (ctx, ct) =>
			{
				if (ctx.Node is not StructDeclarationSyntax structDecl)
					return (ADFilterInfo?)null;
                INamedTypeSymbol? interfaceToImplement = ctx.SemanticModel.Compilation.GetTypeByMetadataName("RhythmBase.Adofai.Components.Filters.IFilter");
                INamedTypeSymbol? specialIdAttribute = ctx.SemanticModel.Compilation.GetTypeByMetadataName("RhythmBase.Global.Converters.RDJsonSpecialIDAttribute");
                INamedTypeSymbol? symbol = ctx.SemanticModel.GetDeclaredSymbol(structDecl);
                if (symbol == null || !symbol.Interfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, interfaceToImplement)))
                    return null;
                AttributeData? attribute =
					symbol.GetAttributes().FirstOrDefault(i => SymbolEqualityComparer.Default.Equals(i.AttributeClass, specialIdAttribute));
                return new ADFilterInfo(symbol, attribute);
            })
			.Where(i => i != null)
			.Select((i, _) => i!.Value)
            .Collect();
		context.RegisterImplementationSourceOutput(types, (spc, type) =>
		{
			StringBuilder sb = new();
			sb.AppendLine("""
			// <auto-generated/>
			namespace RhythmBase.Adofai.Utils;
			partial class FilterTypeUtils{
				private static System.Collections.ObjectModel.ReadOnlyDictionary<string, RhythmBase.Adofai.FilterType> _str2e;
				private static System.Collections.ObjectModel.ReadOnlyDictionary<RhythmBase.Adofai.FilterType, string> _e2str;
				internal static System.Collections.ObjectModel.ReadOnlyDictionary<string, RhythmBase.Adofai.FilterType> _string2enum = new(new Dictionary<string, RhythmBase.Adofai.FilterType>()
				{
			""");
			foreach(var t in type.OrderBy(i=>i.Type.Name))
			{
				string specialName = t.specialNameAttribute?.ConstructorArguments.FirstOrDefault().Value?.ToString() ?? t.Type.Name;
                sb.AppendLine($"""
							["{specialName}"] = RhythmBase.Adofai.FilterType.{t.Type.Name},
					""");
			}
			sb.AppendLine("""
				});
				internal static System.Collections.ObjectModel.ReadOnlyDictionary<RhythmBase.Adofai.FilterType, string> _enum2string = new(new Dictionary<RhythmBase.Adofai.FilterType, string>()
				{
			""");
			foreach(var t in type.OrderBy(i=>i.Type.Name))
			{
				string specialName = t.specialNameAttribute?.ConstructorArguments.FirstOrDefault().Value?.ToString() ?? t.Type.Name;
                sb.AppendLine($"""
							[RhythmBase.Adofai.FilterType.{t.Type.Name}] = "{specialName}",
					""");
			}
			sb.AppendLine("""
				});
			}
			""");
			spc.AddSource($"FilterTypeUtilsForEnum.g.cs", sb.ToString());
        });
    }
}